### ISSUE TITLE
Save config error

### ISSUE THREAD

**Issue by alexlutor** [pfzim/ldap-phonebook#10]
Добрый день! 
Не могу записать конфиг., пишите ошибку "Save config error",
Как отловить ошибку?
Все шаги, по подключению базы, создания пользователя, базы, таблицы, e-mail, создания учетной записи ,- проходят успешно.

Вот что установлено на Linux 
php -ver
PHP 5.6.36 (cli) (built: Apr 25 2018 10:02:39)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

apachectl -ver
Server version: Apache/2.4.6 (CentOS)
Server built:   Apr 20 2018 18:10:38

mysql -V
mysql  Ver 15.1 Distrib 10.3.7-MariaDB, for Linux (x86_64) using readline 5.1

Модули есть:
php --ini | grep fileinfo
/etc/php.d/20-fileinfo.ini,
php --ini | grep ldap
/etc/php.d/20-ldap.ini,

**Comment by pfzim** [comment]
Поверьте права на папку, куда установлен справочник. У пользователя, из-под которого запущен веб сервер, должен быть доступ на запись.
Можете дать доступ только на время установки.
На папку ./photos должны быть права на запись постоянно.

**Comment by alexlutor** [comment]
Спасибо! да, нужны были права на файл, apache мог сохранить файл конфигурации.
