### ISSUE TITLE
Отображение мобильных телефонов только после прохождения авторизации

### ISSUE THREAD

**Issue by AndreyDark** [pfzim/ldap-phonebook#11]
Добрый день!
Не подскажите, как можно сделать, чтобы мобильные номера отображались только после прохождения авторизации на веб интерфейсе книги? Сам понимаю, что нужно просто вторую страничку сделать, которая бы задействовалась после логина, но не смог найти в коде где идет этот самый переход.

**Comment by pfzim** [comment]
Нужно в файле `templ/tpl.main.php` строку 25 заменить на:
```
<?php if($uid) { ?>
	<th width="10%" onclick="sortTable(<?php eh($i++); ?>)">Mobile</th>
<?php } ?>
```
строку 43 заменить на:
```
<?php if($uid) { ?>
	<td><?php eh($row[8]); ?></td>
<?php } ?>
```

**Comment by AndreyDark** [comment]
Благодарю, работает.

**Comment by linuxmangr** [comment]
Вот момент "строку 43 заменить на:" так и не понял где поменять.
![line43](https://user-images.githubusercontent.com/15612072/71003255-d589b380-20f1-11ea-9f9a-bbb6b4a67a8c.png)

Вот на Geany видны строки, подскажите где поменять.

**Comment by pfzim** [comment]
Строка где $row['pcell']
