### ISSUE TITLE
Поиск по номеру

### ISSUE THREAD

**Issue by thdonatello** [pfzim/ldap-phonebook#13]
Возможно ли в строке поиска игнорировать спецсимволы? Номера мобильных телефонов могут быть записаны +7, 7, 8 и пр, для легкого чтения в номере иногда выделяют префикс в скобки, ставят дефисы/пробелы. Поиск же работает по строгому соответствию... Хотя нет, он работает странным образом. При вводе в строку "79" отбираются номера 891, 892, +7(91, 798, при вводе "89" отбираются почти те же диапазоны (ключевое "почти", есть различия). При вводе "791" совсем ничего не находится. При "891" находятся 891, +7(91... 
Я так понимаю, что имеется какая-то реализация замены 8 с +7 и наоборот, но работает она не понятно для меня. Хотелось бы видеть номера в приятном глазу виде и иметь поиск без ввода пробелов, скобок, дефисов.
Спасибо!

**Comment by pfzim** [comment]
Поиск реализован очень плохо, он ищет по html таблице включая html тэги. Это скорее костыль. У меня никак не дойдут руки его передалать.

**Comment by pfzim** [comment]
Переделал поиск. Теперь он выполняется на стороне сервера, но всё также - соответствие должно быть строгим.

**Comment by pfzim** [comment]
Улучшил поиск по номеру. Теперь при поиске учитываются только цифры, остальные символы игнорируются.
