### ISSUE TITLE
Как заменить параметр mobile на ipPhone

### ISSUE THREAD

**Issue by karamelich** [pfzim/ldap-phonebook#15]
Добрый день!
Хотелось бы получить инструкцию на тему замены параметра Mobile (мобильный телефон) на ipPhone.

**Comment by karamelich** [comment]
Всё сделано как Вы говорите,но колонка пустая

**Comment by pfzim** [comment]
Нижний регистр соблюли в названии атрибута и выполнили синхронизацию после изменений?

**Comment by karamelich** [comment]
конечно же нет, поменял регистр и все получилось! Спасибо!

**Comment by drewetmur** [comment]
Прошу прощения за то что не создал новую тему, но мне кажется что вопрос однотипный. 
Так вот, как заменить phone_city на ipphone? Пробовал вариант указанный здесь, с mobile замена работает, а с phone city нет. 
									$s_login = @$account['samaccountname'][0];
									$s_first_name = @$account['givenname'][0];
									$s_last_name = @$account['sn'][0];
									$s_department = @$account['department'][0];
									$s_organization = @$account['company'][0];
									$s_position = @$account['title'][0];
									$s_phone_internal = @$account['telephonenumber'][0];
									$s_phone_mobile = @$account['mobile'][0];
									$s_mail = @$account['mail'][0];
									$s_photo = @$account['thumbnailphoto'][0];
									$s_visible = ((bool)(@$account['useraccountcontrol'][0] & 0x2))?0:1;
Здесь вообще нет phone city

**Comment by pfzim** [comment]
А откуда вы взяли phone city? Я такого атрибута у пользователей AD не нахожу

**Comment by pfzim** [comment]
Duplicate of #25

**Comment by drewetmur** [comment]
> А откуда вы взяли phone city? Я такого атрибута у пользователей AD не нахожу

Вот и я не нашел, здесь есть все атрибуты https://docs.microsoft.com/en-us/windows/win32/adschema/attributes-all но нет про City ничего, однако в коде о нем полно упоминаний.

**Comment by drewetmur** [comment]
\phone\www\language\ru.php (совпадений: 1)
Line 6: 	"mainPhoneCity" =>		"IP телефон",
\phone\www\pb.js (совпадений: 2)
Line 443: 				row.cells[3].setAttribute('id', "pcityCell"+data.data.id);				// Городской телефон
Line 461: 				var phoneCityCell 			= gi("pcityCell"+data.data.id);			// Городской телефон
\phone\www\pb.php (совпадений: 3)
Line 857: 			$s_phone_city 		= trim(@$_POST['phonecity']);
Line 911: 			$s_phone_city, 
Line 940: 			$s_phone_city,

**Comment by drewetmur** [comment]
Ваше предложение: "Сделайте аналогично, как с mobile в #15. В переменную LDAP_ATTRS добавьте новый импортируемый из AD атрибут ipphone. В строке присвоения $s_phone_city замените на ipphone:
$s_phone_city 		= trim(@$_POST['ipphone']);"
Отчасти не работает, так как после добавления атрибута в LDAP_ATTRS атрибут безусловно появляется, проверял заменой mobile, а вот таблица pcity в Базе данных не заполняется.

**Comment by pfzim** [comment]
Я не правильно подсказал, поэтом удалил сообщение. Проложим в #25

**Comment by pfzim** [comment]
Я не правильно подсказал, поэтом удалил сообщение. Проложим в #25
