### ISSUE TITLE
Create admin account

### ISSUE THREAD

**Issue by 99819888** [pfzim/ldap-phonebook#18]
При создании admin получаю ошибку
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('12345'), 'admin@example.com', 0)' at line 1

Server version:         8.0.16 MySQL Community Server - GPL

**Comment by pfzim** [comment]
Видимо, потому что в вашей версии MySQL нет функции PASSWORD.
https://stackoverflow.com/questions/52320576/in-mysql-server-8-0-the-password-function-not-working

**Comment by 99819888** [comment]
Спасибо за быстрый ответ.
Не совсем понял что предпринять для решения. Подскажите пожалуйста что изменить в install.php
для изменения функции PASSWORD.

**Comment by pfzim** [comment]
Попробуйте во всех SQL запросах, где встречается PASSWORD(...), заменить его на MD5(...)

**Comment by 99819888** [comment]
Установил mariadb проблема ушла.
