### ISSUE TITLE
Ошибка при синхронизации с AD

### ISSUE THREAD

**Issue by smale3** [pfzim/ldap-phonebook#19]
При запуске синхронизации возникает ошибка "HTTP ERROR 500".

**Comment by pfzim** [comment]
В логах вебсервера есть какие-нибудь ошибки?

**Comment by smale3** [comment]
PHP Fatal error:  Call to undefined function ldap_connect() in /pb.php on line 371, referer: http://phone.ksk.ru/pb.php

**Comment by pfzim** [comment]
Ваша версия PHP не поддерживает LDAP. Соберите PHP с поддержкой LDAP или подключите модуль, если это Windows.

**Comment by smale3** [comment]
Спасибо за помощь.

**Comment by noragami25** [comment]
PHP Warning:  ldap_bind(): DN contains a null byte in /var/www/html/pb.php
В чем проблема? Вроде все верно указываю

**Comment by pfzim** [comment]
Проверьте внимательнее параметры. Видимо какой-то параметр пустой, либо содержит недопустимый символ

**Comment by karamelich** [comment]
Fatal error: Maximum execution time of 120 seconds exceeded in C:\wamp64\www\ldap-phonebook-master\pb.php on line 388
Я так понимаю что время нужно увеличить но не разобрался где...

**Comment by pfzim** [comment]
Таймаут регулируется параметром max_execution_time в php.ini

**Comment by karamelich** [comment]
Спасибо, всё получилось
