### ISSUE TITLE
Добавить отображение номера комнаты

### ISSUE THREAD

**Issue by epigraphe** [pfzim/ldap-phonebook#2]
Добрый день. Как добавить вывод номера комнаты?
Я пробовал использовать параметр physicalDeliveryOfficeName чтобы показывать данные из строки Office во вкладке General, но никаких данных он не выдает(
У меня не используется строка Company, поэтому я поменял в файле pb.php `$s_organization = @$account['physicalDeliveryOfficeName'][0];`, но в таблице в столбце org ничего не появляется. Я пробовал менять на initials и инициалы появлялись. 
В файле inc.config я добавлял в "LDAP_ATTRS" значение physicalDeliveryOfficeName

**Comment by pfzim** [comment]
Всё правильно делаете, но ещё много где надо внести изменений.
1. Лучше создать отдельный параметр `$s_room = @$account['physicalDeliveryOfficeName'][0];`
2. Добавить новую колонку в БД в таблицу `pb_contacts`
3. Дополнить SQL запросы
4. Добавить новую колонку в шаблон `templ/tpl.main.php`

**Comment by epigraphe** [comment]
Так в том-то и дело, что я пытаюсь просто заменить Сompany на physicalDeliveryOfficeName ничего не происходит. Поэтому я и не создаю новый параметр, не делаю колонки и не меняю запрос. Я даже не пытаюсь вывести это, а просто получить данные в базу. И ничего не происходит.

Если я меняю company на initials, к примеру, то они в колонке появляются. Вот и не пойму в чем проблема, Office во вкладке General в самом AD заполнен.

**Comment by pfzim** [comment]
Company не используется в шаблоне. Я посчитал, что имя компании в таблице будет лишним, т.к. таблица станет очень большая. Эту колонку можно добавить отредактировав файл `templ/tpl.main.php`. Значение для этого столбца будет: `<php? eh($row[5]); ?>`

**Comment by epigraphe** [comment]
Я не пытаюсь выводить в шаблоне, я не могу получить значения номеров комнат из AD. В самой базе MySQL значения не появляются. Проблема только с номером комнаты, остальные значения прилетают как и полагается.

**Comment by pfzim** [comment]
Теперь понял. Попробуйте вообще убрать последний параметр из функции `ldap_search`, чтобы втянуть все параметры из AD, и раскоментируйте строку `print_r($account)`, чтобы посмотреть что вытягивается из AD.

**Comment by pfzim** [comment]
В отдельном файле для теста:
[test_ldap.php](https://github.com/pfzim/ldap-phonebook/blob/dev/other/test_ldap.php)

**Comment by epigraphe** [comment]
test_ldap выдает номер комнаты
```
Array
(
    [sn] => Array
        (
            [count] => 1
            [0] => Иванов
        )

    [0] => sn
    [title] => Array
        (
            [count] => 1
            [0] => Начальник службы
        )

    [1] => title
    [physicaldeliveryofficename] => Array
        (
            [count] => 1
            [0] => 307
        )

    [2] => physicaldeliveryofficename
    [telephonenumber] => Array
        (
            [count] => 1
            [0] => 001
        )
```

**Comment by pfzim** [comment]
Не понимаю, почему LDAP_FILTER влияет на вывод этого атрибута?
Влиять должен только параметр LDAP_ATTRS

**Comment by epigraphe** [comment]
Ой, прошу прощения, действительно LDAP_ATTRS.
Почему же тогда не работает в скрипте, если работает в тестовом файле?

**Comment by pfzim** [comment]
Опечатки не может быть?
Другого варианта пока не вижу

**Comment by pfzim** [comment]
В php ключи массива регистрозависимые.
Надо сделать так: `$s_organization = @$account['physicaldeliveryofficename'][0];`

**Comment by epigraphe** [comment]
Спасибо, заработало. Дело было именно  в регистре, я писал physicalDeliveryOfficeName
