### ISSUE TITLE
Администратор по Умолчанию (admin)

### ISSUE THREAD

**Issue by linuxmangr** [pfzim/ldap-phonebook#21]
Здравствуйте.
Работает на Ура. 
Все вытащил и А.Д. ну все что было прописано для каждого пользователя.
Но есть не знаю проблема ли и так глюк. 
1) Так как подключается к А.Д.  Админ по умолчанию но может войти?
2) как и где  подправить код чтобы показывать Дни рождения есть такая необходимость.

И вот сейчас попробовал в файле   inc.config.php  убрать значение  
define('PB_USE_LDAP_AUTH', 0);  и сразу админ смог зайти без проблем.

**Comment by pfzim** [comment]
Не понял первый вопрос.
По второму - похожий вопрос с добавлением колонки разбирался здесь:
https://github.com/pfzim/ldap-phonebook/issues/5#issuecomment-384962287

**Comment by linuxmangr** [comment]
Ну про первый вопрос объясню подробнее.
При установки я задал пользователя (admin) и пароль.
Но если при этом в файле inc.config.php поставить значение
define('PB_USE_LDAP_AUTH', 1); то выше указанный пользователь не может зайти и это понятно так как он не находится в А.Д. как (admin) но при этом даже пользователи которые имею права в А.Д. на изменение прав пользователей тоже не могут войти даже если задать правильно данные учетной записи:  domain\\login 
Но в принципе работает хорошо если убрать:  1  из  define('PB_USE_LDAP_AUTH', 0).

Ну а про второй вопрос да я видел этот вопрос с добавлением колонки но это не сработает пока не будет добавление дня рождения в А.Д.

**Comment by pfzim** [comment]
Чтобы работала авторизация AD, помимо параметра PB_USE_LDAP_AUTH = 1 нужно указать группу AD в параметре LDAP_ADMIN_GROUP_DN и добавить в эту группу пользователей, которым разрешено редактировать справочник.

**Comment by linuxmangr** [comment]
Спасибо за ответ, попробую добавить.

**Comment by pfzim** [comment]
В новой версии справочника LDAP и локальная аутентификации работают одновременно.
