### ISSUE TITLE
При сохранении конфига выдает: Save config error

### ISSUE THREAD

**Issue by CelicaGT4** [pfzim/ldap-phonebook#22]
В чем может быть проблема? Спасибо

**Comment by pfzim** [comment]
Проверьте права на папку, скорее всего нет доступа на запись у пользователя из-под которого запущен веб сервер.

**Comment by pfzim** [comment]
Дубликат #10

**Comment by CelicaGT4** [comment]
> Проверьте права на папку, скорее всего нет доступа на запись у пользователя из-под которого запущен веб сервер.

Да, ошибка ушла, конфиг сохранился, но вот беда - по итогу ничего не отображается (HTTP ERROR 500)

**Comment by CelicaGT4** [comment]
> > Проверьте права на папку, скорее всего нет доступа на запись у пользователя из-под которого запущен веб сервер.
> 
> Да, ошибка ушла, конфиг сохранился, но вот беда - по итогу ничего не отображается (HTTP ERROR 500)

Поставил авторизацию PB_USE_LDAP_AUTH = 1, справочник отобразился, но никаких данных не подхватывает

**Comment by pfzim** [comment]
Ищите ошибку в логах http сервера, скорее всего не хватает какого-нибудь модуля для php

**Comment by CelicaGT4** [comment]
Модули подключены, в логах такие ошибки сыпятся:
[Mon Mar 16 09:17:52.769200 2020] [php7:warn] [pid 2152] [client 172.16.1.80:52162] PHP Warning:  require_once(/var/www/html/phonebook/language/.php): failed to open stream: No such file or directory in /var/www/html/phonebook/pb.php on line 87
[Mon Mar 16 09:17:52.769304 2020] [php7:error] [pid 2152] [client 172.16.1.80:52162] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/phonebook/language/.php' (include_path='.:/usr/share/php') in /var/www/html/phonebook/pb.php on line 87
[Mon Mar 16 09:18:24.333633 2020] [php7:notice] [pid 2156] [client 172.16.1.80:52166] PHP Notice:  Undefined index: footerLoading in /var/www/html/phonebook/templ/tpl.footer.php on line 4

**Comment by pfzim** [comment]
Проверьте переменную APP_LANGUAGE в inc.config.php. Похоже она не определена

**Comment by CelicaGT4** [comment]
> Проверьте переменную APP_LANGUAGE в inc.config.php. Похоже она не определена

Определял, как "ru", так и "en": язык меняется, но никаких данных не подгружает.

**Comment by pfzim** [comment]
По представленным логам вижу, что переменная APP_LANGUAGE пустая.

Если справочник открывается без ошибок, тогда может быть сначала нужно выполнить синхронизацию для загрузки данных из AD?

**Comment by CelicaGT4** [comment]
> По представленным логам вижу, что переменная APP_LANGUAGE пустая.
> 
> Если справочник открывается без ошибок, тогда может быть сначала нужно выполнить синхронизацию для загрузки данных из AD?

Подскажите, как правильно это сделать? И да, прошу прощения за тупые, возможно, вопросы. Я вообще с LDAP сервисами первый раз сталкиваюсь. Возможно что что-то делаю не так и не совсем понимаю как это работает. Спасибо!

**Comment by pfzim** [comment]
Нужно авторизоваться в справочнике и нажать кнопку Sync, чтобы данные из AD загрузились в его БД.

**Comment by CelicaGT4** [comment]
> Нужно авторизоваться в справочнике и нажать кнопку Sync, чтобы данные из AD загрузились в его БД.

Забавный момент: при конфигурировании он просит создать админский аккаунт Admin, задал пароль и все ок, конфигурация нормально вся сохранилась, к AD есть подключение:
[https://cdn.jpg.wtf/futurico/ed/f4/1584429077-edf4360bb442374514cf497010a8bb73.png](url)

Но под логином Admin не пускает, требует учетки доменной, ввожу свои данные, как при конфигурировании, и получаю ошибку: доступ запрещен. Не понимаю как это работает

**Comment by pfzim** [comment]
Отключите LDAP авторизацию, которую вы включили ранее. Или добавьте свою доменную учетную запись в группу AD, которую указали в конфиге.

**Comment by pfzim** [comment]
В новой версии справочника LDAP и локальная аутентификации работают одновременно.
