### ISSUE TITLE
Синхронизация с LDAP через SSL.

### ISSUE THREAD

**Issue by Artur1232** [pfzim/ldap-phonebook#24]
Доброго дня!
Подскажите пожалуйста, есть ли возможность настроить синхронизацию с сервером LDAP через SSL?

**Comment by pfzim** [comment]
Думаю можно.
Попробуйте изменить строку:
`$ldap = @ldap_connect(LDAP_HOST, LDAP_PORT);`
на
`$ldap = @ldap_connect(LDAP_HOST);`
И в `inc.config.php` в параметре `LDAP_HOST` указать строку подключения к LDAP, как указано в [документации](https://www.php.net/manual/ru/function.ldap-connect.php)

**Comment by Artur1232** [comment]
Все заработало!
Спасибо!

**Comment by pfzim** [comment]
В новой версии справочника параметры `LDAP_HOST` и `LDAP_PORT` заменены на `LDAP_URI`
