### ISSUE TITLE
IP Phone вместо Phone City

### ISSUE THREAD

**Issue by drewetmur** [pfzim/ldap-phonebook#25]
Здравствуйте! Подскажите как и где исправить код, чтоб таблица **pcity** заполнялась данными из AD, а не в ручную. Хочу в это поле выводить IP телефон, но все мои попытки увенчались неудачей. Сама телефонная книга работает отлично. Спасибо за сие творение.

**Comment by pfzim** [comment]
Сделайте аналогично, как с mobile в #15. В переменную `LDAP_ATTRS` добавьте новый импортируемый из AD атрибут `ipphone`. В строке присвоения `$s_phone_city` замените на `ipphone`:
```
$s_phone_city 		= trim(@$_POST['ipphone']);
```

**Comment by pfzim** [comment]
В переменную `LDAP_ATTRS` добавьте новый импортируемый из AD атрибут `ipphone` и примените приложенный патч
[ipphone.patch](https://github.com/pfzim/ldap-phonebook/files/5186307/ipphone.patch.txt)

**Comment by drewetmur** [comment]
Прошу прощения за глупый вопрос, я в php не силен. Как применить данный патч?

**Comment by drewetmur** [comment]
Спасибо, справился, ручками просто добавил все то что указано в патче. Все работает, спасибо огромное, это лучший справочник для LDAP во всем ру нете.

**Comment by drewetmur** [comment]
Продолжу здесь. Так как после внесения изменений в данной теме проблема появляется другая. Теперь ipphone правильно отображается и берется в правильном ID в AD. Но, добавление в ручную по средством mainAddСontact (кнопка добавить контакт, когда есть авторизация) перестало работать, и ajax выдает 2 сообщения Зеленое: "Added (ID 0)" и Красное: "**Invalid identifier**" ошибка идентификатора, который нужно заменить или добавить в pb.js как я полагаю. Если у вас найдется пару минут свободного времени, посмотрите пожалуйста, как исправить данную проблему.

**Comment by pfzim** [comment]
Я никак не доберусь посмотреть. Внесенные патчем изменения не должны были повлиять на добавление контакта. Если вернуть исходный файл, добавление контакта работает?

**Comment by drewetmur** [comment]
Доброго времени суток. Сейчас проверил, не работает и до внесения изменения в файл.

**Comment by drewetmur** [comment]
Сделал чистую установку, тоже не работает.

**Comment by pfzim** [comment]
Исправил ошибку. Проблема была при сохранении локального контакта без заполненного поля День рождения. По всей видимости старая версия MySQL допускала сохранение пустой даты.
Обновите у себя файл pb.php и проверьте.

**Comment by drewetmur** [comment]
Отлично. Внес изменения в  pb.php все стало работать. Спасибо за поддержку и решение проблем.

**Comment by olegww** [comment]
Доброго времени! Автору респект!
Поделитесь пожалуйста полным списком изменений для решения этой задачи. Прочитал 2е дискуссии касаемо этой проблемы, внес изменения для текущей версии
inc.config.php
`define('LDAP_ATTRS', 'samaccountname,ou,sn,givenname,mail,department,company,title,telephonenumber,mobile,thumbnailphoto,useraccountcontrol,ipphone');`
pb.php
`859 $s_phone_city 		= trim(@$_POST['ipphone']);`
`1073 "ipphone": "'.json_escape($row["pcity"]).'",`
`933 `ipphone` = !,`
`903 `ipphone`,`
патч ipphone.patch я так понимаю в текущей версии уже применен.
после синхронизации в бд таблице pcity не подтягивает данные.
Подскажите какие изменения еще нужно вносить.
Спасибо!

**Comment by drewetmur** [comment]
О как, у меня ночь уже, а завтра выходные, как посмотрю что я делал, подскажу. Оно все у меня на работе, а на работу я пока не собираюсь.

**Comment by drewetmur** [comment]
Патч был не применен, не всем ужена данная функция. Думаю после применения патча, все заработает.

**Comment by olegww** [comment]
Благодарю за подсказку. На чистый файл применил патч и в конфиге добавил ipphone и все заработало.
Добавил отображение колонки Организация в шаблоне, в бд уже все было.
Если вдруг кому нужно
tpl.main.php
найти 
`<th width="15%" onclick="sortTable(<?php eh($i++); ?>)"><?php eh($lang["mainPosition"]) ?></th>`
добавить после
`<th width="5%" onclick="sortTable(<?php eh($i++); ?>)"><?php eh($lang["mainOrganisation"]) ?></th>`
найти
`<td id="<?php eh("posCell".$row["id"]);?>"><?php eh($row["pos"]); ?></td>`
добавить после
`<td id="<?php eh("orgCell".$row["id"]);?>"><?php eh($row["org"]); ?></td>`

language/ru.php
в секцию //----tpl.main.php
добавить
"mainOrganisation"			=>  	"Организация",

Ширину столбцов настраивайте под себя изменяя  width="%"
```
 				<th width="15%" onclick="sortTable(<?php eh($i++); ?>)"><?php eh($lang["mainName"]) ?></th>
				<th width="5%" onclick="sortTable(<?php eh($i++); ?>)"><?php eh($lang["mainPhone"]) ?></th>
				<th width="5%" onclick="sortTable(<?php eh($i++); ?>)"><?php eh($lang["mainPhoneCity"]) ?></th>
				<th width="5%" onclick="sortTable(<?php eh($i++); ?>)"><?php eh($lang["mainMobile"]) ?></th>
				<th width="10%" onclick="sortTable(<?php eh($i++); ?>)"><?php eh($lang["mainEMail"]) ?></th>
				<th width="20%" onclick="sortTable(<?php eh($i++); ?>)"><?php eh($lang["mainPosition"]) ?></th>
				<th width="10%" onclick="sortTable(<?php eh($i++); ?>)"><?php eh($lang["mainOrganisation"]) ?></th>
				<th width="15%" onclick="sortTable(<?php eh($i++); ?>)"><?php eh($lang["mainDepartment"]) ?></th>
				<?php if($user->get_id()) { ?>
				<th width="15%"><?php eh($lang["mainOperations"]) ?></th>
```
Всем добра!
