### ISSUE TITLE
Автоматическое обновление (cron)

### ISSUE THREAD

**Issue by alexdaft** [pfzim/ldap-phonebook#27]
Можно ли реализовать обновление данных с AD посредством цикличной cron задачи без рукоприкладства со стороны администратора web-gui ?

**Comment by pfzim** [comment]
Можно. Не понимаю в чем сложность?

**Comment by alexdaft** [comment]
Хотелось бы знать какой в данном случае php дергать

**Comment by pfzim** [comment]
Всё тоже самое, что делаете через веб, эмулируете через cron.
http://localhost/pb/pb.php?action=sync

**Comment by alexdaft** [comment]
Благодарю!

**Comment by drewetmur** [comment]
Приветствую. Ребята напишите конкретно команду, я уже пробую который час в cron добавляю, но ни как не получается. Спасибо заранее. У меня debian 10, но думаю это не сильно важно.

**Comment by alexdaft** [comment]
> 
> 
> Приветствую. Ребята напишите конкретно команду, я уже пробую который час в cron добавляю, но ни как не получается. Спасибо заранее. У меня debian 10, но думаю это не сильно важно.

у меня прописано следующим образом

$ crontab -l
*/30 * * * * curl -k https://phonebook.nucrf.net/pb.php?action=sync >/dev/null 2>&1
*/30 * * * * curl -k https://phonebook.nucrf.net/pb.php?action=hide_disabled >/dev/null 2>&1

вроде все работает, но если я где то ошибся, pfzim надеюсь поправит.

**Comment by alexdaft** [comment]
> 
> 
> Приветствую. Ребята напишите конкретно команду, я уже пробую который час в cron добавляю, но ни как не получается. Спасибо заранее. У меня debian 10, но думаю это не сильно важно.

у меня оно прописано следующим образом:

**Comment by drewetmur** [comment]
Благодарю. Теперь стало гораздо понятнее.

**Comment by drewetmur** [comment]
Проблема следующего характера, при выполнении команды получаю 301 Moved Permanently, и информация не обновляется. Не могу понять что я делаю не так. Возможно ли, что это из за того что нужна авторизация для обновления?

**Comment by pfzim** [comment]
Добрый день!

Проблем в том, что вы забываете про Cookie и не выполняете аутентификацию. Первым шагом надо выполнить вход и получить Cookie zl и zh из ответа. Далее подставлять их в вышеприведённые запросы.

zh обнуляется при Logoff. Если создать отдельную учетную запись для синхронизации и не делать Logoff, то этот токен будет постоянным. Его можно подсмотреть в запросах браузера или БД. Тогда не придется эмулировать аутентификацию в скрипте cron.

**Comment by pfzim** [comment]
Добавил в меню Tools показ текущего токена и пример использования с curl. Возможно пример не совсем точный, т.к. в данный момент негде протестировать.

**Comment by drewetmur** [comment]
Вы все правильно говорите, просто у меня все гораздо сложнее. Развернут web сервер на котором крутятся несколько сайтов, в том числе и телефонный справочник, по этой причине localhost и hostname не работают с сервера. debian установлен без KDE и GNOM и иных оболочек, по этому нормальный браузер запустить не получится. И вот через голую консоль, я авторизоваться не представляю как. Устанавливал w3m (вроде поддерживает cookie), запускал, авторизовался, но куков не нашел, если запускать с рабочей машинки, то писать curl бесполезно так как авторизация в браузере на другом ПК, это такое себе. А отдельный сервер поднимать ради того чтоб работала синхронизация, не горю желанием. Может я где то не очень хорошо разбираюсь в apache и nginx, но реализовать то что вы предлагаете не могу. Интересно есть ли еще какие либо способы? Вроде запуска скрипта, который авторизуется или выполняет команду синхронизации.

**Comment by alexdaft** [comment]
Вспомнил, что копался в коде и вырезал из него часть касаемо авторизации, т.к. сервер только во внутренней сети да еще и скрытый дополнительным фронтом. по этому у меня отрабатывала синхронизация без необходимости вводить куки.

**Comment by drewetmur** [comment]
> Вспомнил, что копался в коде и вырезал из него часть касаемо авторизации, т.к. сервер только во внутренней сети да еще и скрытый дополнительным фронтом. по этому у меня отрабатывала синхронизация без необходимости вводить куки.

Вот это уже интересно. В каком месте этот код? 
Думаю если убрать с кнопки синхронизации, функцию "срабатывать только после авторизации" это решит проблему. А при настроенной авто синхронизации, кнопку можно будет просто скрыть и она не понадобится вовсе. 
У меня просто и сотовые телефоны в базе, а они доступны только после авторизации.

**Comment by drewetmur** [comment]
Решено!
Закомментировал в pb.php
```
case 'sync':
		{
			//if(!$user->get_id()) break;
```
 И сделал crontab -e
*/1 * * * * curl -k https://site.name.com/pb.php?action=sync >/dev/null 2>&1
*/1* * * * curl -k https://site.name.com/pb.php?action=hide_disabled >/dev/null 2>&1
теперь все отрабатывает. А кнопка осталась в меню, после авторизации, для ручной синхронизации.

**Comment by pfzim** [comment]
>  так как авторизация в браузере на другом ПК

Не важно с какого ПК забирать cookie. Главное не выполнять Logout, чтобы их не обнулить

**Comment by pfzim** [comment]
Нет, запуск из bash не поддерживается. Но наработки в этом направлении есть в соседнем проекте WebSCO. Возможно когда-то и добавлю в телефонный справочник, если время появится.
curl же умеет аутентификацию!?

**Comment by morzhov** [comment]
Помимо парольной аутентификации curl должен уметь и Kerberos.

Вот с такой комбинацией `curl --negotiate -u admin  -b /home/user/PBULMGTA.cookie -c /home/user/PBULMGTA.cookie http://srv-phonebook.corp.domain.ru/pb.php?action=sync` curl запрашивает пароль админа, аутентифицируется, но обновления не происходит. Когда это делаешь с кнопки из браузера все ОК. 
Cookie файл я вытащил из истории IE.

**Comment by pfzim** [comment]
Обновил справочник. В новой версии добавил возможность запуска команд из консоли. Поддерживается аутентификация.
Примеры команд есть в разделе Tools.

**Comment by morzhov** [comment]
Спасибо!
`php -f /var/www/html/phonebook/pb.php -- --user admin --password <password> --path contacts_sync`
Выбрал данный вариант. Работает.
А вот синхронизация отключенных в АД пользователей не работает, что командой в шелле, что ссылкой http://srv-phonebook.domain.local/pb.php?path=contacts_hide_disabled

**Comment by pfzim** [comment]
Исправил опечатку в скрипте синхронизации.

Показывать вновь включенные не получится. Если я так сделаю, то при каждой синхронизации будут показываться все контакты, которые вы скрывали вручню.

**Comment by pfzim** [comment]
> После того, как юзер был отключен в АД и скрыт в PB, а затем вновь включен в АД, в PB не прилетает.

Добавил команду `contacts_show_all_enabled` - показать в списке все контакты, которые "включены" в AD. Это должно решить вашу проблему.
