### ISSUE TITLE
Установка телефонного справочника без подключения Active Directory

### ISSUE THREAD

**Issue by vnazarkin** [pfzim/ldap-phonebook#28]
Добрый день!
В рекомендуемых требованиях у вас написано что Active Directory (optional), т.е. наличие AD опционально и не обязательно.
Однако без AD я не могу установить ваш телефонный справочник через мастер установки, подскажите пожалуйста, как быть в данном случае?

**Comment by pfzim** [comment]
При установке введите любые значение и пропустите проверку
