### ISSUE TITLE
Не подтягиваются аватарки

### ISSUE THREAD

**Issue by trracert** [pfzim/ldap-phonebook#29]
Развернул справочник, синхронизировал с AD, но аватарки пользователей не подтянулись. Что можно поправить, чтобы устранить это?
![image](https://user-images.githubusercontent.com/73105195/96687436-8d2dc880-1388-11eb-812d-91dde8a82727.png)

**Comment by pfzim** [comment]
Проверьте права на директорию photos. Скорее всего при синхронизации справочник не может их сохранить

**Comment by trracert** [comment]
Вы были правы, спасибо )
chmod -R 777 /var/www/html/phonebook/photos/ -- помогло
