### ISSUE TITLE
Экспорт изображения.

### ISSUE THREAD

**Issue by epigraphe** [pfzim/ldap-phonebook#3]
Какая колонка в файле tpl.export отвечает за вывод фотографии?
`<?php eh($row[]); ?>`

**Comment by pfzim** [comment]
Фотографии хранятся в директории `photos`.
Имя файла: `t1.jpg`, где `1` - это id контакта из БД (`<?php eh($row[]); ?>`).
В БД хранится только флаг - есть фотка у контакта или нет
