### ISSUE TITLE
ошибка первого входа после установки

### ISSUE THREAD

**Issue by Smoky555** [pfzim/ldap-phonebook#30]
Установил, настроил, все проверки система прошла. При первом входе ошибка 500. В логах сервера текст "PHP Parse error:  syntax error, unexpected ')', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in /var/www/html/ldph/pb.php on line 134"
система - centos 7, PHP 5.4.16 

информация о модулях:

LDAP Support | enabled
RCS Version | $Id$
Total Links | 0/unlimited
API Version | 3001
Vendor Name | OpenLDAP
Vendor Version | 20444
SASL Support | Enabled

**Comment by Smoky555** [comment]
сам решил... на новой версии php не работает оператор empty. В 134 строке скрипта поменял его на defined - все заработало.

**Comment by pfzim** [comment]
Очень странно. У меня на PHP 7.4.13 empty работает.
Возможно вы удалили из inc.config.php параметр LDAP_ADMIN_GROUP_DN.
На всякий случай добавил дополнительную проверку defined.
