### ISSUE TITLE
Ошибка при добавлении пользователя

### ISSUE THREAD

**Issue by Torin88** [pfzim/ldap-phonebook#32]
Добрый день.
У меня во время использования начала появляться ошибка при попытках добавить пользователя "руками". Всплывает два сообщения: на зеленом фоне "added (ID 0)" и сразу другое на красном "Invalid Identifier". При этом пользователи из AD загружаются и обновляются без проблем. Проблема в ручном добавлении. Скорее всего это началось после того, как я вернулся к старой точке восстановления на виртуальной машине, на которой установлен веб сервис.
Как я понял, сервис пытается создать новую запись в базе данных с ID = 0, но SQL это сделать не позволяет.
Что я делал для устранения ошибки: Создавал новую базу, как руками, так и через "install.php", создавал нового пользователя для БД, вручную переделывал ID одного из действующих адресатов на ID=0. Ничего не помогло. Подскажите, куда копать?
![image](https://user-images.githubusercontent.com/81558158/113389078-144f8580-9398-11eb-90c5-2d4a52ce55ec.png)

**Comment by pfzim** [comment]
Первое сообщение с ID равным нулю, говорит о том, что INSERT в базу данных из строки 895 не отработал. Далее происходит попытка подгрузить новую запись в таблицу, но т.к. она не создалась и идентификатор не корректный = 0, то видим вторую ошибку.

Надо разбираться почему не проходит SQL запрос. Если не заполняете поле день рождения, то возможно вашему SQL серверу не нравится значение даты '0000-00-00'.

В код вносили изменения?

**Comment by Torin88** [comment]
Попробовал внести пользователя с датой рождения. Создаётся. 
Поправил строчку else{$s_bday = '0000-00-00';} на else{$s_bday = '0000-01-01';} - Создаётся. 
Предполагаю, что так как тип столбца bday - date, то он принимает только значение даты, а дата не может иметь значение 0 месяца или 0 числа. Звучит логично, но как это работало раньше - ума не приложу.

В сам код почти не лез, только файлик ru.php и сортировку подправил.

**Comment by pfzim** [comment]
На различных версиях MySQL/MariaDB работает по-разному
