### ISSUE TITLE
Отображение "выводимого имени" вместо фамилии и имени

### ISSUE THREAD

**Issue by yukh975** [pfzim/ldap-phonebook#34]
Сложно ли сделать вывод поля "выводимое имя" вместо фамилии и имени?
Очень неудобно отсутствие отчества в списке сотрудников.

**Comment by pfzim** [comment]
Не сложно. Если по-быстрому, то можно заменить `givenname` на `displayname`, а `$s_last_name` сделать пустым. В конфиге в `LDAP_ATTRS` нужно добавить `displayname`. Мне не на чем сейчас тестить.

```
$s_first_name = @$account['displayname'][0]; 
$s_last_name = '';
```
https://github.com/pfzim/ldap-phonebook/blob/c9d219c9f25731b2c1453dd8287e1115fe1966a3/pb.php#L367-L368

**Comment by yukh975** [comment]
Спасибо, завтра будем пробовать. О результатах отпишусь.
