### ISSUE TITLE
Скрыть столбец "Городской телефон".

### ISSUE THREAD

**Issue by morzhov** [pfzim/ldap-phonebook#35]
Спасибо за ваш труд!
Подскажите пожалуйста, каким образом можно скрыть столбец "Городской телефон"?

**Comment by pfzim** [comment]
Просто отредактируйте шаблон страницы `templ/tpl.main.php`, удалив ненужный столбец из таблицы

**Comment by morzhov** [comment]
Да, я так делал, удалял:
`<th width="10%" onclick="sortTable(<?php eh($i++); ?>)"><?php eh($lang["mainPhoneCity"]) ?></th>`
но тогда в столбец e-mail, попадают мобильные телефоны, а в столбец должность - email, таблица съезжает.

**Comment by morzhov** [comment]
Спасибо!

**Comment by Grimturs** [comment]
Привет.
Удалил в двух местах. В общем виде всё хорошо, но если выполнить поиск, то содержание колонок сдвигается.
Не смог найти, где можно исправить. Кто-нибудь сталкивался, где искать?

Кусок кода с основной таблицей из tpl.contacts.php:
`		<table id="table" class="main-table">
			<thead>
			<tr>
				<?php $i = 0; ?>
				<?php if($is_admin) { ?>
				<th width="1%"><input type="checkbox" onclick="f_select_all(event)"/></th>
				<?php $i++; } ?>
				<th width="15%"><a href="<?php ln($action.'/sort/'.(0 | ((($sort & 0xFF) == 0 && ($sort & 0x0100) == 0)?0x0100:0)).'/offset/'.$offset.'/search/'.urlencode($search)); ?>"><?php L('Name') ?></a><?php if(($sort & 0xFF) == 0) { echo ' '.(($sort & 0x0100)?'&#9660;':'&#9650;'); } ?></th>
				<th width="10%"><a href="<?php ln($action.'/sort/'.(1 | ((($sort & 0xFF) == 1 && ($sort & 0x0100) == 0)?0x0100:0)).'/offset/'.$offset.'/search/'.urlencode($search)); ?>"><?php L('Phone') ?></a><?php if(($sort & 0xFF) == 1) { echo ' '.(($sort & 0x0100)?'&#9660;':'&#9650;'); } ?></th>
				<th width="10%"><a href="<?php ln($action.'/sort/'.(2 | ((($sort & 0xFF) == 2 && ($sort & 0x0100) == 0)?0x0100:0)).'/offset/'.$offset.'/search/'.urlencode($search)); ?>"><?php L('Mobile') ?></a><?php if(($sort & 0xFF) == 2) { echo ' '.(($sort & 0x0100)?'&#9660;':'&#9650;'); } ?></th>
				<th width="15%"><a href="<?php ln($action.'/sort/'.(3 | ((($sort & 0xFF) == 3 && ($sort & 0x0100) == 0)?0x0100:0)).'/offset/'.$offset.'/search/'.urlencode($search)); ?>"><?php L('Mail') ?></a><?php if(($sort & 0xFF) == 3) { echo ' '.(($sort & 0x0100)?'&#9660;':'&#9650;'); } ?></th>
				<th width="30%"><a href="<?php ln($action.'/sort/'.(4 | ((($sort & 0xFF) == 4 && ($sort & 0x0100) == 0)?0x0100:0)).'/offset/'.$offset.'/search/'.urlencode($search)); ?>"><?php L('Position') ?></a><?php if(($sort & 0xFF) == 4) { echo ' '.(($sort & 0x0100)?'&#9660;':'&#9650;'); } ?></th>
				<th width="15%"><a href="<?php ln($action.'/sort/'.(5 | ((($sort & 0xFF) == 5 && ($sort & 0x0100) == 0)?0x0100:0)).'/offset/'.$offset.'/search/'.urlencode($search)); ?>"><?php L('Department') ?></a><?php if(($sort & 0xFF) == 5) { echo ' '.(($sort & 0x0100)?'&#9660;':'&#9650;'); } ?></th>
				<?php if($is_admin) { ?>
				<th width="15%"><?php L('Operations') ?></th>
				<?php } ?>
			</tr>
			</thead>
			<tbody id="table-data">
		<?php $i = 0; foreach($phones as &$row) { $i++; ?>
			<tr id="<?php eh("row".$row['id']);?>" data-id=<?php eh($row['id']);?> data-map=<?php eh($row['map']); ?> data-x=<?php eh($row['x']); ?> data-y=<?php eh($row['y']); ?> data-flags=<?php eh($row['flags']); ?>>
				<?php if($is_admin) { ?>
					<td><input type="checkbox" name="check" value="<?php eh($row['id']); ?>"/></td>
				<?php } ?>
				<td onclick="f_sw_map(event);" onmouseenter="f_sw_img(event);" onmouseleave="gi('imgblock').style.display = 'none'" onmousemove="f_mv_img(event);" style="cursor: pointer;" class="<?php if(intval($row['flags']) & PB_CONTACT_WITH_PHOTO) { eh('userwithphoto'); } ?>"><?php eh($row['last_name'].' '.$row['first_name'].' '.$row['middle_name']); ?></td>
				<td><?php eh($row['phone_internal']); ?></td>
				<td><?php eh($row['phone_mobile']); ?></td>
				<td><a href="mailto:<?php eh($row['mail']); ?>"><?php eh($row['mail']); ?></a></td>
				<td><?php eh($row['position']); ?></td>
				<td><?php eh($row['department']); ?></td>
				<?php if($is_admin) { ?>
					<td>
						<span class="command" onclick="f_menu(event);"><?php L('Menu') ?></span>
					</td>
				<?php } ?>
			</tr>
		<?php } ?>
			</tbody>
		</table>`

**Comment by Grimturs** [comment]
Заметил следующую закономерность.
Сдвиг происходить только на моменте ввода запроса в поле "Find: Search...". Если выполнить поиск (нажать Enter или кнопку Search), то отображение восстанавливается.

**Comment by ssstheman** [comment]
такой же вопрос, как скрыть ненужные столбцы?
выше написано что в файле templ/tpl.main.php но я такой не нахожу

**Comment by pfzim** [comment]
@ssstheman вам нужен файл `templates/tpl.contacts.php` (поменялось расположение и имя файла).

**Comment by ssstheman** [comment]
тут убрал, но у меня тоже как в посте выше - при поиске сдвигаются поля

чт, 14 сент. 2023 г. в 13:37, pfzim ***@***.***>:

**Comment by pfzim** [comment]
> тут убрал, но у меня тоже как в посте выше - при поиске сдвигаются поля

Нужно ещё вот здесь в функции `fill_contacts` поправить:
https://github.com/pfzim/ldap-phonebook/blob/07ebd8facda154ae571201465c16b488f4a96489/pb.js#L1395-L1405
