### ISSUE TITLE
Скорость работы базы

### ISSUE THREAD

**Issue by jiki7** [pfzim/ldap-phonebook#38]
Добрый день.
Подскажите, пожалуйста, почему справочник на Windows Server 2019 работает быстрее, чем на Windows 10?
Т.е. у меня Windows 10 + Hyper-V и на виртуалке Windows Server 2019 в 10 раз быстрее работает добавление контактов вручную, чем если у меня все так же поднято на Windows 10. Именно меню это на сайте справочника "добавить контакт" молниеносно открывается на Windows Server 2019, а на Windows 10 и phpmyadmin висит по 10 секунд после каждого нажатия и меню "добавить контакт" на сайте справочника тоже. Ссылаюсь, что, возможно, проблема в какой-то низкой скорости работы базы MariaDB на Windows 10. Что необходимо доустановить или поднастроить, чтобы у меня на локальном хосте на Windows 10 сайт справочника работал очень быстро? На Windows Server 2019, видимо, уже какие-то интересные компоненты предустановлены, что сайт справочника и phpmyadmin просто летают...

**Comment by pfzim** [comment]
В этом я вам точно не подскажу. На мой взгляд немного извращение MariaDB устанавливать на Windows. Это больше для тестов, разработки подходит.
Поднимите сервер на Linux.
