### ISSUE TITLE
Дублируется информация в пустые поля контактов

### ISSUE THREAD

**Issue by jiki7** [pfzim/ldap-phonebook#39]
Добрый день.
Описываю ситуацию, которую заметил и хотел бы решение как отключить эту зависимость:
Есть Контакт №1, у которого заполнены все поля в форме добавления контакта.
Есть Контакт №2, у которого заполнены 2 первых поля и много пустых полей.
Есть Контакт №3, у которого заполнены 2 последних поля, а остальные пустые.
Если, например, нажать кнопку Изменить Контакта №1, внести изменения в любое заполненное поле, потом нажать кнопку Сохранить и не обновлять страницу, то при нажатии кнопки Изменить у Контакта №2 все пустые поля "втихоря" заполняются информацией из полей Контакта №1, что редко замечаешь вообще, нажимаешь Сохранить и потом получается что e-mail, телефон и т.п. одинаковые у разных сотрудников. Контакт №3, например, заполнит пустые поля информацией из заполненных полей Контакта №2 и т.д.
Когда массово меняю всем контактам адреса, например, то данная опция совершенно неудобна мне.
Решение есть конечно, но неудобное, необходимо после изменения полей Контакта №1 и нажатия кнопки Сохранить, нажимать F5 и только после этого можно править поля других контактов и не боятся, что информация задублируется, но не всегда вспоминаешь об обновлении страницы после редактирования каждого контакта в массовом режиме.
Где эта строчка кода, которая за это отвечает?
Хотелось бы ее закомментировать, чтобы было удобно массово изменять контакты не обновляя страницу каждый раз и чтобы информация не подтягивалась туда-сюда лишняя.
Спасибо.

**Comment by pfzim** [comment]
Что-то у меня не получается воспроизвести вашу проблему. Добавьте скриншотов, может понятнее станет о чем вы говорите.

Это не функционал, а баг - я такое поведение не предусматривал.

**Comment by jiki7** [comment]
Скриншоты во вложении.
1. Есть 2 контакта.
2. Сведения о Контакте №1.
3. Изменяем некоторые поля у Контакта №1 и нажимаем сохранить.
4. Видим, что изменилось и сразу же открываем Контакт №2 для редактирования не обновляя страницу.
5. Видим, что пустые поля Контакта №2 заполнились измененной информацией из полей Контакта №1.
6. Но если после каждого раза как отредактировал любой контакт рефрешить страницу, то все хорошо.

![1  Есть 2 контакта](https://user-images.githubusercontent.com/98803900/153546605-29f2b6e6-c07b-4422-b263-e431326c33f4.jpg)
![2  Сведения о Контакте №1](https://user-images.githubusercontent.com/98803900/153546606-eac2c68f-1267-4d17-9d86-9a860e704571.jpg)
![3  Изменяем некоторые поля у Контакта №1 и нажимаем сохранить](https://user-images.githubusercontent.com/98803900/153546608-b077296b-e4ae-4475-b015-914de9ff52d6.jpg)
![4  Видим, что изменилось и сразу же открываем Контакт №2 для редактирования](https://user-images.githubusercontent.com/98803900/153546609-e17792fe-0804-49ff-b2de-271d6f8a912a.jpg)
![5  Видим, что пустые поля Контакта №2 заполнились измененной информацией из полей Контакта №1](https://user-images.githubusercontent.com/98803900/153546610-00168aee-a505-4f50-bdce-c7a6693253d2.jpg)

**Comment by pfzim** [comment]
У вас какая-то старая версия справочника судя по скриншоту окна редактирования.
Установите последнюю

**Comment by jiki7** [comment]
Я же ведь переделал под себя там поля, колонки, отображения там всякие, стили...
Это же все исчезнет после обновления?

**Comment by pfzim** [comment]
Да, все изменения перезапишутся

**Comment by jiki7** [comment]
Уже нашел, поэтому коммент и удалил. Спасибо.
