### ISSUE TITLE
 Названия комнат в карте

### ISSUE THREAD

**Issue by stration** [pfzim/ldap-phonebook#4]
Можно ли поменять названия комнат в карте Floor 1, Floor 3, Floor 6, Floor14, Floor 25 ?
На Этаж 1, Этаж 2, Филиал 7, Центральный офис.

**Comment by pfzim** [comment]
Да, можно. Надо поменять в файле `inc.config.php` значения переменных `PB_MAPS_COUNT` и `$map_names`

**Comment by stration** [comment]
в файле inc.config.php нет переменной $map_names

**Comment by pfzim** [comment]
Возможно у вас старая версия справочника, либо вы смотрите пример конфга в директории `other`.
Обновите справочник и добавьте в файл `inc.config.php`, который лежит в корне, строку:
`$map_names = array("Floor 1", "Floor 3", "Floor 6", "Floor 14", "Floor 25");`

**Comment by stration** [comment]
Версия справочника с GitHub, там файл inc.config.php только в директории other.
Если есть где то обновленная версия дайте ссылочку или обновите на GitHub. 
Спасибо.

**Comment by stration** [comment]
Ой... сори не доглядел, в корне он тоже есть. Спасибо, все нормально.
