### ISSUE TITLE
Первый запуск / install.php

### ISSUE THREAD

**Issue by Grimturs** [pfzim/ldap-phonebook#40]
Привет.
Благодарю за интересный проект, мне он очень понравился, но я не очень дружу с линейкой ОС линукс (только учусь).
На CentOS 7 были развёрнуты Apache, PHP и MariaDB. Проверил работу, подсунув в каталог "/var/www/html" простенький index.php. Далее подсунул в эту же директорию ваш проект. При открытии сайта идёт переадресация на страницу install.php, но страница не открывается, появляется ошибка:
Страница недоступна
Сайт 192.168.11.11 пока не может обработать этот запрос.
HTTP ERROR 500

Прошу подсказать куда копать.
Если есть полная инструкция по развёртыванию проекта, то буду признателен, если подскажете где её найти.

**Comment by pfzim** [comment]
Добрый день!

Посмотрите какая ошибка в логах Apache (/var/log/.../error.log)

**Comment by Grimturs** [comment]
Благодарю за быструю обратную связь.
Проблема была в версии php. Была установлена 5,4. Обновил до 7,1 - заработало.
Прошу прощения за беспокойство.

**Comment by Grimturs** [comment]
Добрый день.
Столкнулся с несколькими проблемами:
1. не удаётся сохранить конфигурацию через install.php (10 пункт). Получаю ошибку:
"Save config error. Check write permissions to /var/www/html/"
Пробовал выставлять на папку права 777, результат тот же.

Скачивал конфиг и добавлял его руками, но страница pb.php открывается с ошибкой
"HTTP ERROR 500"
В логах ошибка доступа к базе данных, хотя проверка в install.php сообщала, что доступ есть.

2. не удаётся проверить соединение с домен контроллерами (7 пункт), ошибка
"Can't contact LDAP server"
Порты открыты, учётная запись имеет права на чтение каталога.

Прошу подсказать, куда копать.
Могу воспроизвести проблему и предоставить необходимые логи.

**Comment by Grimturs** [comment]
Коллеги, постоянно сталкиваюсь с проблемами на этапе развёртывания..
Есть у кого инструкция? Буду признателен, если вы ей поделитесь.
В linux только вхожу, поэтому не знаю нюансов/отличий операционных систем. Да, можно отправить много читать и это будет большим опытом для меня, но мне очень нравится проект и хочется его поскорее реализовать.

Мне будет достаточно подсказать какую ОС (версию) брать, какой репозиторий использовать и какой php ставить.
С остальным проблем, вроде, нет.
До этого пробовал CentOS 7, Stream-8/9, Debian. Но везде сталкивался с проблемами php, то версия не подходила (не открывалась страница), то модулей не хватало (в репозиториях отсутствовали для определённых версий).. Проблемы подключение ldap, думаю тоже были связаны с модулем php.

В общем плюсики в карму всем небезучастным!

**Comment by pfzim** [comment]
Просите, не хватает времени заниматься справочником. Ещё это дикое охуевание в связи с войной с Украиной и вообще с ситуацией в стране, что ничего делать не хочется.

В установке все должно быть просто. К версии PHP он  не сильно должент быть привязан, т.к. я не использовал каких-либо новшеств языка. На PHP 7+ должен нормально работать. Проще наверно ставить на Debian, вроде все из родного репозитория тянется.

Странно, что у вас при инсталляции проверка LDAP проходит, вот после уже не работает. Пока даже не знаю, что посоветовать.

В логах Апача нет подробной ошибки?

**Comment by Grimturs** [comment]
Благодарю за обратную связь.
Поставил последнюю версию debian и из стандартных репозиториев удалось установить все компоненты.
