### ISSUE TITLE
Отображение ФИО в списке,

### ISSUE THREAD

**Issue by yukh975** [pfzim/ldap-phonebook#41]
После обновления пропала возможность выводить ФИО (отображаемое имя) вместо отдельных полей фамилия и имя.
Ранее обсуждалось, было решение вопроса, сейчас этот метод не работает.

**Comment by Grimturs** [comment]
Привет.
Разверул у себя последний релиз и у меня получилось заменить Ф.И. на отображаемое имя.
Решение в ветке обсуждений https://github.com/pfzim/ldap-phonebook/issues/34. Правда не совсем точное.
С новыми релизами изменились названия файлов и переменных.

Нужно в файле /routes/contacts_sync.php внести изменения:
Добавить в строку атрибут "displayname" _примерно 29 строка_
`
['objectguid', 'samaccountname' , 'sn', 'displayname', 'initials', 'middleName', 'givenname', 'mail', 'department', 'company', 'title', 'telephonenumber', 'mobile', 'thumbnailphoto', 'useraccountcontrol'],
`
и
Изменить значения переменных _примерно 67-68 стоки_
`
$v_first_name = @$entries[$i]['givenname'][0];
$v_last_name = @$entries[$i]['sn'][0];
`
заменить на

**Comment by yukh975** [comment]
Спасибо за наводку, у меня получилось примерно вот так:

['objectguid', 'samaccountname' , 'sn', 'displayname', 'initials', 'middleName', 'givenname', 'mail', 'department', 'company', 'title', 'telephonenumber', 'mobile', 'thumbnailphoto', 'useraccountcontrol'],

// $v_first_name = @$entries[$i]['givenname'][0];
$v_first_name = @$entries[$i]['displayname'][0];
$v_last_name = '';// @$entries[$i]['sn'][0];
$v_middle_name = ''; //@$entries[$i]['middlename'][0];

**Comment by apollon8825** [comment]
Спасибо за предоставленное решение, воспользовался им
