### ISSUE TITLE
Ошибка: tpl.users.php 

### ISSUE THREAD

**Issue by yukh975** [pfzim/ldap-phonebook#42]
Warning: include(/var/www/webapps/pb/templates/tpl.tree-list.php): failed to open stream: No such file or directory in /var/www/webapps/pb/templates/tpl.users.php on line 2

Warning: include(): Failed opening '/var/www/webapps/pb/templates/tpl.tree-list.php' for inclusion (include_path='./:/usr/share/php/pear/:/usr/share/php/modules/') in /var/www/webapps/pb/templates/tpl.users.php on line 2
Управление локальными пользователями

В текущем релизе файл отсутствует.
Как решить?

**Comment by pfzim** [comment]
Это лишняя ссылка на файл из другого проекта затесалась. Уберу в ближайшее время

**Comment by pfzim** [comment]
Исправил
