### ISSUE TITLE
Фотографии пользователей

### ISSUE THREAD

**Issue by Grimturs** [pfzim/ldap-phonebook#44]
Приветствую.
Прошу подсказать как реализовать отображение фотографий пользователей, выгруженных не из AD, а, например, из сетевой папки? Уж очень маленькие размеры фотографий в AD. Для страницы "Map" идеальные, но для станицы "Contacts" маленькие.
Так же это усложняет поддержку фото пользователей, т.к. им нужно загружать фото самостоятельно (по крайней мере я знаю только такой способ - через owa).
Может есть ещё какой альтернативный метод..?

**Comment by pfzim** [comment]
Просто так не подсказать. Надо садиться и писать код. Аналогично и по второму вопросу #43

**Comment by pfzim** [comment]
Загрузка и сохранение фото происходит в этом блоке:
https://github.com/pfzim/ldap-phonebook/blob/b5b6ee267f83a86fbf4322a5b1bfe1ef5dbee579/routes/contacts_sync.php#L246-L273

Замените этот блок на свой код.
