### ISSUE TITLE
Отключение обновление

### ISSUE THREAD

**Issue by dacent89** [pfzim/ldap-phonebook#45]
Как можно отключить обновление, при запуске пытается обновить.
А при нажатии upgrade ошибки:

`Upgrading...

Create 'config' table...
Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Add column 'ldap' to 'users' table...
Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Set db_version = '1'...
Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Upgrade to version 1 complete!

Add column 'type' to 'contacts' table...
Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Set db_version = '2'...
Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

Now you must add to inc.config.php something like

  $g_icons = array("Human", "Printer", "Fax");
And replace files templ/marker-static-[0-nn].png with you icons

Upgrade to version 2 complete!

Create 'handshake' table...
Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Set db_version = '3'...
Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

Upgrade to version 3 complete!`

**Comment by pfzim** [comment]
Вы видимо обновили файлы справочника? Теперь он не может подключиться к БД, чтобы обновить её.
Покажите свой конфиг.
