### ISSUE TITLE
ошибка при запуске проекта 

### ISSUE THREAD

**Issue by pablo2025** [pfzim/ldap-phonebook#46]
Спасибо за ваш отличный проект. Я пытаюсь запустить проект на локальном хосте. После добавления папки в папку htdocs xampp меня перенаправляют на страницу install.php.

Я ввожу необходимые пароли и учетные данные, но затем, когда я пытаюсь получить доступ к индексной странице, я получаю эту ошибку: 

` Fatal error: Uncaught mysqli_sql_exception: Access denied for user 'dbuser'@'localhost' (using password: YES) in ...\xampp\htdocs\ldap-phonebook-master\modules\MySQLDB.php:95 Stack trace: #0 ...\xampp\htdocs\ldap-phonebook-master\modules\MySQLDB.php(95): mysqli_connect('localhost', 'dbuser', '123456', 'websco') #1 ...\xampp\htdocs\ldap-phonebook-master\modules\MySQLDB.php(223): MySQLDB->connect(true) #2 ...\xampp\htdocs\ldap-phonebook-master\modules\Config.php(33): MySQLDB->select_ex(Array, 'SELECT m.`name`...') #3 ...\xampp\htdocs\ldap-phonebook-master\modules\Config.php(62): Config->load(0) #4 D:\xampp\htdocs\ldap-phonebook-master\modules\Config.php(80): Config->get_ex(0, 'db_version', 0) #5 ...\xampp\htdocs\ldap-phonebook-master\pb.php(150): Config->get_global('db_version', 0) #6 {main} thrown in ...\xampp\htdocs\ldap-phonebook-master\modules\MySQLDB.php on line 95`

что случилось?

**Comment by pfzim** [comment]
Проверьте, что пользователь базы данных dbuser создался и пароль корректный
