### ISSUE TITLE
Не синхронизирует LDAP

### ISSUE THREAD

**Issue by serdgserdg** [pfzim/ldap-phonebook#47]
При нажатии "Синхронизировать"
выдает ошибку
Exception: File: C:\pb\routes\contacts_sync.php[44]: ldap_parse_result return error: Success Trace: 
#0 C:\pb\modules\Router.php(103): contacts_sync(Object(Core), Array, Array)
#1 C:\pb\pb.php(316): Router->process('contacts_sync', Array)
#2 {main}
Но в тоже время зайти как администратор с доменной учетной записью удается.

**Comment by pfzim** [comment]
Расширил вывод при ошибке. Обновите справочник и попробуйте синхронизировать ещё раз.
Текст ошибки должен получится более подробным.

**Comment by serdgserdg** [comment]
2022-03-29T12:16:44+03:00 
Exception: File: C:\pb\routes\contacts_sync.php[49]: ldap_parse_result return error code: , message: , ldap_error: Success Trace: 
#0 C:\pb\modules\Router.php(103): contacts_sync(Object(Core), Array, Array)
#1 C:\pb\pb.php(316): Router->process('contacts_sync', Array)
#2 {main}

**Comment by pfzim** [comment]
Очень странно. А при инсталляция проверка подключения к LDAP успешно завершалась?
Случаем не LDAPS используете для подключения?

**Comment by serdgserdg** [comment]
1. Check loaded PHP modules ldap - OK
SimpleXML - OK
memcached - missing
json - OK
curl - OK
pcre - OK
gd - OK
mysqli - OK
2. Check DB connection 
OK
3. Create database 
OK
4. Create tables 
OK
5. Create DB user 
OK
6. Grant access to database 
OK
7. Check LDAP connection 
OK (Entries founded: 279)
9. Create admin account 
OK
при инсталляция проверка подключения к LDAP успешна и группу админов добавил без проблем, и заходит под доменной
проверил доступность LDAP - все работает "LDAP bind successful..."
$ldapuser = domain\user";
$ldappass = "passwd";
$ldapserver = "LDAP.domain.local:389";

$ad = ldap_connect("ldap://".$ldapserver) or die("Cant connect to LDAP Server");
ldap_set_option($ad, LDAP_OPT_PROTOCOL_VERSION, 3);
$adbind = ldap_bind($ad, $ldapuser, $ldappass);
if ($adbind)
{
    echo "LDAP bind successful...";
}
else
{
    echo "LDAP bind failed...";
}

?>

**Comment by pfzim** [comment]
Не знаю в чём может быть проблема.

У вас `ldap_parse_result` почему-то возвращает FALSE, но следом `ldap_error` говорит Success.

```
		if(!ldap_parse_result($core->LDAP->get_link(), $result, $errcode , $matcheddn , $errmsg , $referrals, $controls))
		{
			throw new Exception('ldap_parse_result return error code: '.$errcode.', message: '.$errmsg.', ldap_error: '.ldap_error($core->LDAP->get_link()));
		}

```

Мне встречалось похожее поведение с криптографических функций используемых PHPMailer'ом. Проблема решилась настройкой OpenSSH. Но у вас шифрование не используется и подключение успешно проходит.

Напишите, если получится выяснить в чем проблема.

**Comment by serdgserdg** [comment]
Сначала использовал iss, подумал что проблема в нем.
Установил ubuntu 20,04 + nginx + php 7.4.
В итоге  install.php отображает пустую страницу

**Comment by pfzim** [comment]
А что в логах?

**Comment by serdgserdg** [comment]
thrown in /var/www/pb/pb.php on line 54" while reading response header from upstream, client: 192.168.10.101, server: _, request: "GET /pb.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.0-fpm.sock:", host: "192.168.141.62"
2022/03/30 11:19:39 [error] 20410#20410: *84 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/var/www/pb/modules/Core.php): Failed to open stream: Permission denied in /var/www/pb/pb.php on line 54PHP message: PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/pb/modules/Core.php' (include_path='.:/usr/share/php') in /var/www/pb/pb.php:54
Stack trace:
#0 {main}

**Comment by pfzim** [comment]
Похоже, что не хватает прав на чтение файла var/www/pb/modules/Core.php

**Comment by serdgserdg** [comment]
выполнил команды
sudo chmod -R 0755 /var/www/pb/modules/Core.php
sudo chmod -R 0755 /var/www/pb/modules
теперь нет ошибок в /var/log/nginx/error.log

**Comment by serdgserdg** [comment]
![image](https://user-images.githubusercontent.com/38786467/160800746-3a035346-bde3-4db5-ab7e-3a44e5c037d8.png)

**Comment by pfzim** [comment]
Проверьте на остальные файлы и папки права. Возможно к файлам шаблона тоже нет доступа

**Comment by serdgserdg** [comment]
заработало и контакты синхронизировались
