### ISSUE TITLE
Фильтр отображаемых столбцов

### ISSUE THREAD

**Issue by serdgserdg** [pfzim/ldap-phonebook#48]
Подскажите как установить фильтр отображения столбцов для пользователя который не авторизовался?

**Comment by serdgserdg** [comment]
В предыдущих версиях можно было по @uid  как организованно в этой версии?

**Comment by serdgserdg** [comment]
реши при помощи
?php if($is_admin) { ?>
<?php } ?>
в файле tpl.contacts.php

**Comment by pfzim** [comment]
Всё правильно сделали. Так и надо было

**Comment by serdgserdg** [comment]
только при использовании поиска теперь не правильно формирует таблицу . Не сдвигает отображаемые данные в нужный столбец

**Comment by pfzim** [comment]
Вот здесь ещё исправьте:
https://github.com/pfzim/ldap-phonebook/blob/92ba12e2da66eaaa400d25f4b9dc389eca5d36d4/pb.js#L1395-L1405

**Comment by serdgserdg** [comment]
спасибо!
всё получилось
