### ISSUE TITLE
Ф.И.О.

### ISSUE THREAD

**Issue by stration** [pfzim/ldap-phonebook#5]
Здравствуйте.
Как сделать чтобы в колонке (Name) ФИО шли в алфавитном порядке?
Спасибо.

**Comment by pfzim** [comment]
Нужно в файле pb.php в строке 739 изменить ORDER BY в SQL запросе:
`$db->select(rpv("SELECT m.`id`, m.`samname`, m.`fname`, m.`lname`, m.`dep`, m.`org`, m.`pos`, m.`pint`, m.`pcell`, m.`mail`, m.`photo`, m.`map`, m.`x`, m.`y`, m.`visible` FROM `@contacts` AS m WHERE m.`visible` = 1 ORDER BY m.`lname`, m.`fname`"));`
По умолчанию сортируется по фамилии. Чтобы сортировалось по имени, изменить на:
`ORDER BY m.`fname`, m.`lname`"));`

**Comment by thdonatello** [comment]
Доброго дня!
Подскажите, а как поменять местами отображение fname и lname, что бы сначала была фамилия?
Большое спасибо.

**Comment by pfzim** [comment]
Нужно в файле tpl.main.php строку 32:
```
<td onclick="f_sw_map(event);" onmouseenter="f_sw_img(event);" onmouseleave="gi('imgblock').style.display = 'none'" onmousemove="f_mv_img(event);" style="cursor: pointer;" class="<?php if(intval($row[10])) { eh('userwithphoto'); } ?>"><?php eh($row[2].' '.$row[3]); ?></td>
```
заменить на
```
<td onclick="f_sw_map(event);" onmouseenter="f_sw_img(event);" onmouseleave="gi('imgblock').style.display = 'none'" onmousemove="f_mv_img(event);" style="cursor: pointer;" class="<?php if(intval($row[10])) { eh('userwithphoto'); } ?>"><?php eh($row[3].' '.$row[2]); ?></td>
```

**Comment by AndreyDark** [comment]
Добрый день!
Подскажите, пожалуйста, как добавить в столбце "name" отображение отчества сотрудника? По умолчанию отображается имя, фамилия.

**Comment by serdgserdg** [comment]
Отображение отчества! 
1. Добавляем в базу, в конец еще одна колонку "patronymic"
2. в файле inc.config.php 
правим строку 15
define("LDAP_ATTRS", "samaccountname,ou,sn,givenname,mail,department,company,title,telephonenumber,mobile,thumbnailphoto,useraccountcontrol,middlename");

3. В файле pb.php строки

добавляем строку после 325
$s_pname = @$account['middlename'][0];
правим строку 334
$db->put(rpv("UPDATE `@contacts` SET `fname` = !, `patronymic` = !, `lname` = !, `dep` = !, `org` = !, `pos` = !, `pint` = !, `pcell` = !, `mail` = !, `photo` = # WHERE `samname` = ! LIMIT 1", $s_first_name, $s_pname, $s_last_name, $s_department, $s_organization, $s_position, $s_phone_internal, $s_phone_mobile, $s_mail, isset($account['thumbnailphoto'][0])?1:0, $s_login));

правим строку 339
$db->put(rpv("INSERT INTO `@contacts` (`samname`, `fname`, `patronymic`, `lname`, `dep`, `org`, `pos`, `pint`, `pcell`, `mail`, `photo`, `visible`) VALUES (!, !, !, !, !, !, !, !, !, !, #, 1)", $s_login, $s_first_name, $s_pname, $s_last_name, $s_department, $s_organization, $s_position, $s_phone_internal, $s_phone_mobile, $s_mail, isset($account['thumbnailphoto'][0])?1:0));

дописываем строку после 358
$s_pname

правим строку 441
if($s_disabled && $db->select(rpv("SELECT m.`id`, m.`samname`, m.`fname`, m.`patronymic`, m.`lname`, m.`dep`, m.`org`, m.`pos`, m.`pint`, m.`pcell`, m.`mail`, m.`photo`, m.`map`, m.`x`, m.`y`, m.`visible` FROM `@contacts` AS m WHERE m.`samname` = ! AND m.`visible` = 1 LIMIT 1", $s_login)))

дописывает строку после 644
$s_pname = @$_POST['patronymic'];
 
правим строку 650
$db->put(rpv("INSERT INTO `@contacts` (`samname`, `fname`, `lname`, `dep`, `org`, `pos`, `pint`, `pcell`, `mail`, `photo`, `photo`, `patronymic`,) VALUES ('', !, !, !, !, !, !, !, !, #, 1, !)", $s_first_name, $s_last_name, $s_department, $s_organization, $s_position, $s_phone_internal, $s_phone_mobile, $s_mail, $s_photo,$s_pname));

правим строку 656
$db->put(rpv("UPDATE `@contacts` SET `fname` = !, `lname` = !, `dep` = !, `org` = !, `pos` = !, `pint` = !, `pcell` = !, `mail` = !, `photo` = #, `patronymic` = !, WHERE `id` = # AND `samname` = '' LIMIT 1", $s_first_name, $s_last_name, $s_department, $s_organization, $s_position, $s_phone_internal, $s_phone_mobile, $s_mail, $s_photo, $s_pname, $id));

правим строку 695
 if(!$db->select(rpv("SELECT m.`id`, m.`samname`, m.`fname`, m.`lname`, m.`dep`, m.`org`, m.`pos`, m.`pint`, m.`pcell`, m.`mail`, m.`photo`, m.`map`, m.`x`, m.`y`, m.`visible`, m.`patronymic` FROM `@contacts` AS m WHERE m.`id` = # LIMIT 1", $id)))

правим строку 701
echo '{"code": 0, "id": '.intval($db->data[0][0]).', "samname": "'.json_escape($db->data[0][1]).'", "firstname": "'.json_escape($db->data[0][2]).'", "lastname": "'.json_escape($db->data[0][3]).'", "department": "'.json_escape($db->data[0][4]).'", "company": "'.json_escape($db->data[0][5]).'", "position": "'.json_escape($db->data[0][6]).'", "phone": "'.json_escape($db->data[0][7]).'", "mobile": "'.json_escape($db->data[0][8]).'", "mail": "'.json_escape($db->data[0][9]).'", "photo": '.intval($db->data[0][10]).', "map": '.intval($db->data[0][11]).', "x": '.intval($db->data[0][12]).', "y": '.intval($db->data[0][13]).', "visible": '.intval($db->data[0][14]).', "patronymic": '.intval($db->data[0][15]).'}';

правим строку 728
$db->select(rpv("SELECT m.`id`, m.`samname`, m.`fname`, m.`lname`, m.`dep`, m.`org`, m.`pos`, m.`pint`, m.`pcell`, m.`mail`, m.`photo`, m.`map`, m.`x`, m.`y`, m.`visible` FROM `@contacts` AS m WHERE m.`visible` = 1 AND m.`map` = # ORDER BY m.`lname`, m.`fname`, m.`patronymic`", $id));

правим строку 737
$db->select(rpv("SELECT m.`id`, m.`samname`, m.`fname`, m.`lname`, m.`dep`, m.`org`, m.`pos`, m.`pint`, m.`pcell`, m.`mail`, m.`photo`, m.`map`, m.`x`, m.`y`, m.`visible`, m.`patronymic` FROM `@contacts` AS m ORDER BY m.`lname`, m.`fname` m.`patronymic`"));

правим строку 746
$db->select(rpv("SELECT m.`id`, m.`samname`, m.`fname`, m.`lname`, m.`dep`, m.`org`, m.`pos`, m.`pint`, m.`pcell`, m.`mail`, m.`photo`, m.`map`, m.`x`, m.`y`, m.`visible`, m.`patronymic` FROM `@contacts` AS m WHERE m.`visible` = 1 ORDER BY m.`lname`, m.`fname`, m.`patronymic`"));

файл tpl.main.php 
правим строку 35
pointer;" class="<?php if(intval($row[10])) { eh('userwithphoto'); } ?>"><?php eh($row[3].' '.$row[2].' '.$row[15]); ?></td>

вроде все!
В АД отчество вписываем в "middlename" он же "OtherName"

**Comment by linuxmangr** [comment]
У меня только один вопрос строки которые указываете в каком editor вы правите?
У меня допустим  есть: xed (Небольшой легковесный текстовый редактор), Geany (Быстрая и легковесная среда разработки "Rezer"), Sublime Text and mc - GNU Midnight Commander)
И ни в одном из выше перечисленных строки почти не совпадаю, согласен кое-где я нашел то что надо и подправил, вроде заработало.
Но вопрос интересен чем вы их правите и строки указываете.
Спасибо.

**Comment by serdgserdg** [comment]
Notepad++
--
Отправлено из Mail.ru для Android понедельник, 16 декабря 2019г., 09:46 +03:00 от Sergios (aka linuxman)  notifications@github.com :

**Comment by stration** [comment]
Можно в простом блокноте или блокнот++.  Это же простой текстовый файл.

пн, 16 дек. 2019 г., 9:46 Sergios (aka linuxman) <notifications@github.com>:

**Comment by serdgserdg** [comment]
Можно и в простом блокноте, но там не видно номер строки. 
Я редактировал этим https://notepad-plus-plus.org
--
Отправлено из Mail.ru для Android понедельник, 16 декабря 2019г., 09:50 +03:00 от stration  notifications@github.com :

**Comment by linuxmangr** [comment]
Я знаю что это текстовой файл и не это меня интересовало, а только то что именно используется.
Но блокнот на винде вы серьезно?Как был полный отстой так и остался, даже номальный текстовой файл на UTF8 иногда если не всегда не в состоянии открыть.
Так работаю на Linux Mint, то придется попробовать открыть их на Виртуальной Винде там он у меня есть.
Спасибо за ответ.

**Comment by pfzim** [comment]
Не вижу разницы какой редактор использовать. Строки могли немного сместиться после обновлений

**Comment by stration** [comment]
https://losst.ru/analogi-notepad-dlya-linux#i
Аналоги notepad++ для Linux

пн, 16 дек. 2019 г. в 20:51, pfzim <notifications@github.com>:

**Comment by linuxmangr** [comment]
Ну как раз я и использую почти всегда  Geany.
Попробую найти все строки. 
Понятно что могли сместится но надо попробовать сделать.

**Comment by serdgserdg** [comment]
Какие вы файлы правите?
Давайте я вам пришлю готовые файлы с исправлениями?
--
Отправлено из Mail.ru для Android вторник, 17 декабря 2019г., 16:53 +03:00 от Sergios (aka linuxman)  notifications@github.com :

**Comment by linuxmangr** [comment]
Я правлю файлы которые вы описываете выше. 
Но хотел бы показывать день рождения за место отчества, по крайне мере для тех кто будет занесен вручную а не через А.Д.
Ну если не трудно вам это сделать я был бы признателен.

**Comment by stration** [comment]
К сожалению разработка не моя. Я сам связывался с разработчиком для
исправления проблемы выше.
И посмотреть сейчас не могу, так как этот проект остался на другой работе,
где я уже не работаю.

вт, 17 дек. 2019 г. в 17:36, Sergios (aka linuxman) <
notifications@github.com>:

**Comment by linuxmangr** [comment]
Понятно, спасибо за советы которые даете.

**Comment by serdgserdg** [comment]
>Вторник, 17 декабря 2019, 17:36 +03:00 от Sergios (aka linuxman) <notifications@github.com>:
>
>Я правлю файлы которые вы описываете выше.
>Но хотел бы показывать день рождения за место отчества, по крайне мере для тех кто будет занесен вручную а не через А.Д.
>Ну если не трудно вам это сделать я был бы признателен.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

Насонов С.А.

**Comment by pfzim** [comment]
Минимальная поддержка для дней рождения уже зашита в проект. Вам нужно определиться в каком атрибуте AD вы будете хранить дату. Добавить загрузку этого атрибута при синхронизации (sync). Добавить колонку для отображения в шаблон.

**Comment by linuxmangr** [comment]
Да, я это уже понял что нужно определится с этим. Ну а Колонку можно поменять из тех что есть что вышло показ дня рождения.
Если это получится я сообщу.

**Comment by trracert** [comment]
https://github.com/pfzim/ldap-phonebook/issues/5#issuecomment-384962287
Пробовал делать, как в комментарии выше, но максимум чего смог добиться это появилась колонка ФИО и она пустая (пропали вытянутые из AD контакты). Как сейчас добавить Отчество? Качал master.zip сегодня.
И второй похожий вопрос: как добавить столбец Организация?
PS Почему нельзя использовать атрибут DisplayName, а не givenName и sn? Вроде меньше заморочек получается с отображением ФИО.

**Comment by pfzim** [comment]
Я не могу подстроить справочник под каждого. Рассматривайте его как шаблон, который нужно править самостоятельно под свои нужды.

1. Требуется добавить в таблицу базы данных новое поле, которое вам необходимо
2. Заполнять это поле во время синхронизации данными из AD
3. Добавить новое поле в SQL запросы
4. Скорректировать HTML шаблоны

**Comment by Kilyakov** [comment]
У кого то получилось добавить поле "Отчество", повторил все как описано выше, ничего не получилось, строки не совпадают в описании.
