### ISSUE TITLE
Проблема с автоматическим скрытием отключенных юзеров

### ISSUE THREAD

**Issue by pochepin** [pfzim/ldap-phonebook#50]
Прошу помощи. При добавлении в crontab `php -f /var/www/telbooks/pb.php -- --user "user" --password "pas" --path contacts_hide_disabled` скрываются все контакты, где ошибка?

**Comment by pfzim** [comment]
У вас случаем не параллельно запускается синхронизация `contacts_sync` и скрытие `contacts_hide_disabled`?
Потому что в начале синхронизации все контакты помечаются, как удалённые и процессе загрузки из AD этот флаг постепенно снимается у существующих контактов. В итоге помеченные удалёнными остаются только те контакты, которые отсутствуют в AD.

**Comment by pochepin** [comment]
Да, именно так. Спасибо за подсказку, изменил время запуска скрытия отключенных контактов. Проверю и отпишусь.
Спасибо Вам за интересный и полезный проект.

**Comment by pfzim** [comment]
Лучше в один файл последовательно добавьте команды, а уже его запускайте из cron.

```
#!/bin/sh

php -f /var/www/telbooks/pb.php -- --user "user" --password "pas" --path contacts_sync
php -f /var/www/telbooks/pb.php -- --user "user" --password "pas" --path contacts_hide_disabled
```

Либо можно одной строкой через `;` сразу в cron.

`php -f /var/www/telbooks/pb.php -- --user "user" --password "pas" --path contacts_sync; php -f /var/www/telbooks/pb.php -- --user "user" --password "pas" --path contacts_hide_disabled`

**Comment by pochepin** [comment]
Огромное Вам спасибо, все работает
