### ISSUE TITLE
Вкладка "Рукопожатия"

### ISSUE THREAD

**Issue by serdgserdg** [pfzim/ldap-phonebook#51]
Вкладка "Рукопожатия" пустая.
Я так понял она нужна для сопоставления компьютеров с учетными записями пользователей.
Подскажите как заполнить ее данными?

**Comment by pfzim** [comment]
Для её заполнения с компьютера пользователя нужно отправить HTTP POST запрос по адресу:
`http://SERVER_ADDRESS_HERE/pb/pb.php?path=hello`
Тело запроса:
`user=<user_name>&comp=<computer_name>`

Можете использовать PowerShell скрипт `https://github.com/pfzim/ldap-phonebook/blob/master/examples/logon-script-hello.ps1` добавив его в автозагрузку на компьютеры пользователей или как логон скрипт групповой политики.

**Comment by serdgserdg** [comment]
Исключение при вызове "GetResponse" с "0" аргументами: "Удаленный сервер возвратил ошибку: (404) Не найден."
+ [System.Net.HttpWebResponse] $response = $request.GetResponse()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Невозможно вызвать метод для выражения со значением NULL.
+ $streamReader = New-Object System.IO.StreamReader($response.GetRespon ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

по чему-то пустой $request.GetResponse() 
но в переменной $request есть данные

**Comment by pfzim** [comment]
Проверьте правильность указанного адреса в скрипте.
У вас ответ сервера: (404) Не найден.

**Comment by serdgserdg** [comment]
Спасибо, всё получилось!
настроил выполнение скрипта: Запуск программы - "powershell.exe" Аргумент  "-WindowStyle Hidden -ExecutionPolicy Bypass -command C:\***путь***\logon-script-hello.ps1
