### ISSUE TITLE
Про регистрацию локальных пользователей

### ISSUE THREAD

**Issue by YuriySam** [pfzim/ldap-phonebook#54]
Дмитрий, Здравствуйте!
А Вы не планируете сделать опцию первичной регистрации для локальных пользователей, чтоб Телефонный справочник им открывался с доступом только для чтения, и  ТОЛЬКО после ввода их Имени и Пароля, которые предварительно введены для них Администратором?

**Comment by pfzim** [comment]
Добрый день, Юрий!

Не планировал. Вы можете самостоятельно это реализовать.

В `pb.php` переместите 
```
	$core->Router->add_route('contacts', 'contacts');						// default route
	$core->Router->add_route('contacts_search', 'contacts', TRUE);

	$core->Router->add_route('map', 'map');

	$core->Router->add_route('contact_get', 'contact_get', TRUE);
	$core->Router->add_route('contact_location_set', 'contact_location_set', TRUE);
```
ниже в блок `else`.
Это должно решить вашу проблему.

**Comment by YuriySam** [comment]
Спасибо. Пробую.

**Comment by YuriySam** [comment]
Спасибо! Получилось!
А как можно убрать из строки меню пункты меню, которые видны, хотя и неактивны, у неавторизированного пользователя, это пункты Главная и Карта.

**Comment by pfzim** [comment]
Их тоже перенесите внутрь условия `if($core->UserAuth->get_id())` в файле `templates/tpl.header.php`

**Comment by YuriySam** [comment]
Спасибо! Получилось!
Рассуждал так: первый пользователь Справочника, - это Администратор (id=1). 

Хочу посоветоваться, как Вы думаете, удачная ли идея, с точки зрения реализации,  добавить поле level (уровень пользователя) в таблицу pb_users с возможностью устанавливать следующие значения:
 1- администратор, он может все.
 2- сотрудник, он может поменять рабочее место на карте
 3 - пользователь только смотреть
Готов попробовать реализовать.

**Comment by pfzim** [comment]
Всё не так.
get_id возвращает идентификатор пользователя. Не нулевое значение означает, что пользователь успешно авторизован.
Локальные пользователи всегда являются администраторами.
Доменные пользователи бесправны, если они не являются членами одной из групп в разделе Разрешения и у этой группы проставлен флажок Администратор.

![image](https://user-images.githubusercontent.com/6803907/174835172-0dc7f366-fc5d-40e0-a05c-b2c0a5bc9240.png)

**Comment by pfzim** [comment]
Разрешения проверяются функцией `check_permission`. Пример:
```
$core->UserAuth->check_permission(0, PB_ACCESS_ADMIN)
```

**Comment by pfzim** [comment]
Если нужны именно локальные пользователи, то думаю проще добавить новый флаг UA_ADMIN.
И в функции `check_permission` исправить на что-то подобное:
```
if(!$this->is_ldap_user())
{
  return ($this->flags & UA_ADMIN) == UA_ADMIN;
}
```

**Comment by pfzim** [comment]
Добавил разделение на непривилегированные и административные учётные записи в ветке dev:
https://github.com/pfzim/ldap-phonebook/tree/dev

**Comment by YuriySam** [comment]
Спасибо! Смотрю...
