### ISSUE TITLE
Синхронизация LDAP Zimbra

### ISSUE THREAD

**Issue by BarmaleyXX** [pfzim/ldap-phonebook#56]
Добрый день.
Хочу сказать Большое спасибо разработчику. Я установил, настроил, запустил, но есть вопросы по синхронизации контактов.
Есть ли возможность синхронизации контактов из OpenLDAP от почтового сервера Zimbra? 
Я правильно понимаю что синтаксис LDAP и AD отличается? в файле inc.config.php по дефолту указано `(&(objectCategory=person)(objectClass=user)(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))`. При запуске синхронизации, выдается результат `Added: 0, Updated: 0` .
Посмотрел схему LDAP зимбры, прописал `(&(objectClass=zimbraAccount)(zimbraAccountStatus=active)))`, что бы пока только синхронизировались только активные учетки, но результат тот же `Added: 0, Updated: 0`.
Подскажите, пожалуйста, как правильно установить параметр PB_LDAP_FILTER.

Спасибо.

**Comment by pfzim** [comment]
Не смогу подсказать, потому что никогда не работал с Zimbra.
Попробуйте поиграться с ldapsearch. Вот здесь есть какие-то примеры: https://wiki.zimbra.com/wiki/ShanxT-LDAP-CheatSheet#Find_an_account_based_on_an_ldap_attribute_-_zimbra_sa
Могу предположить, что отличаются не только LDAP запросы, но и отдаваемые атрибуты, поэтому не проходит синхронизация. Тогда вам придется править скрипт синхронизации contacts_sync

**Comment by BarmaleyXX** [comment]
Про атрибуты это верно подмечено. А можно ли как-нибудь отдельно выполнить процедуру `$result = ldap_search` из крипта синхронизации contacts_sync, что бы посмотреть её результаты? В тот же лог, например. Изменил атрибуты на атрибуты из зимбры, пока результат тот же

**Comment by pfzim** [comment]
В examples лежит скрипт test_ldap.php. С ним поиграйтесь
