### ISSUE TITLE
Не синхронизируются день рождения. 

### ISSUE THREAD

**Issue by serdgserdg** [pfzim/ldap-phonebook#57]
Заменил у себя файл /routes/contacts_sync.php
В AD заполнил данные в поле инфо согласно шаблону. Но данные так и не синхронизируются.

**Comment by pfzim** [comment]
Покажите скриншот заполеннного поля и что поменяли в скрипте

**Comment by serdgserdg** [comment]
Взят  именно ваш файл contacts_sync.php с изменениями от 25 июня, в котором в строке 29 добавлен парамерет 'info'
$core->db->put(rpv('UPDATE `@contacts` SET `flags` = (`flags` | {%PB_CONTACT_AD_DELETED}) WHERE `adid` <> \'\''));

	do
	{
		$result = ldap_search(
			$core->LDAP->get_link(),
			LDAP_BASE_DN,
			PB_LDAP_FILTER,
			['objectguid', 'samaccountname' , 'sn', 'initials', 'middleName', 'givenname', 'mail', 'department', 'company', 'title', 'telephonenumber', 'mobile', 'thumbnailphoto', 'useraccountcontrol', 'info'],
			0,
			0,
			0,
			LDAP_DEREF_NEVER,
			[['oid' => LDAP_CONTROL_PAGEDRESULTS, 'value' => ['size' => 200, 'cookie' => $cookie]]]
		);

**Comment by serdgserdg** [comment]
пробовал добавить в ручную в базу в таблицу pb_contacts , в столбец  birthday добавить дату. все сработало, ближайший Д.Р. отобразился корректно. Проблема именно при синхронизации поля info адресной книги.

**Comment by serdgserdg** [comment]
версия базы 6

**Comment by serdgserdg** [comment]
Исправил, не обратил внимание что нужно креме даты писать выражение BIRTHDAY:
