### ISSUE TITLE
Permissions for AD group

### ISSUE THREAD

**Issue by Grimturs** [pfzim/ldap-phonebook#59]
Приветствую, друг.

Прошу помощи. Решил обслуживать телефонный справочник не локальными учётными записями, а предоставить доступ группам AD, в дальнейшем закрыв доступ неавторизованным пользователям.
Но при добавлении группы получаю сообщение "Group not found in AD". При попытке редактировать права добавленной группы получаю ошибку "Failed get DN by SID".
При этом обновление учётных записей проходит без проблем (LDAP работает).
Подскажи, пожалуйста, в какую сторону копать.

**Comment by pfzim** [comment]
Когда группу добавляете, вводите правильный DistinguishedName группы?
Autocomplete предлагает список групп при вводе?

**Comment by Grimturs** [comment]
Да, правильный.
CN=Phonebook-Admin,OU=Security,OU=Groups,OU=my,DC=int,DC=domain,DC=ru
Autocomplete предлагает только список ранее введённых вариантов distinguishedName групп.

**Comment by Grimturs** [comment]
Не знаю, связано или нет, но при попытке добавить группу AD с чекбоксами "Apply to childs" и "Replace childs" появляется ошибка:
`Exception: File: /var/www/html/modules/Core.php[107]: Core: Table 'websco.pb_runbooks_folders' doesn't exist Trace: #0 /var/www/html/modules/Core.php(100): Core->error_ex() #1 /var/www/html/modules/MySQLDB.php(267): Core->error() #2 /var/www/html/routes/permission_save.php(110): MySQLDB->select_assoc_ex() #3 /var/www/html/routes/permission_save.php(154): permissions_apply_to_childs() #4 /var/www/html/modules/Router.php(103): permission_save() #5 /var/www/html/pb.php(316): Router->process() #6 {main}`

**Comment by pfzim** [comment]
Пока не знаю в чём может быть проблема. Обычно если у кого-то не работает, то не работает в целом LDAP и синхронизация.
Версия справочника последняя?

**Comment by Grimturs** [comment]
Спасибо за обратную связь.
Нашел причину. В inc.config.php, стоит нацеливание на определённую OU, чтобы не цеплять лишние учётки.
define('LDAP_BASE_DN', 'OU=Users,OU=Accounts,OU=my,DC=int,DC=domain,DC=ru');

Можно ли обойти это нацеливание для добавление групп?

**Comment by pfzim** [comment]
Нет, такого не предусмотрено. Если только сами допишете.

**Comment by Grimturs** [comment]
Благодарю
