### ISSUE TITLE
Отсутствие кнопок

### ISSUE THREAD

**Issue by Alexey163** [pfzim/ldap-phonebook#6]
Доброго времени суток.
Подскажи пожалуйста. При авторизации под админом отсутствуют кнопка редактирования абонента, удаления, добавления фото.  Так же при удалении контакта из AD абонент в базе остается. Так и задумано?

**Comment by pfzim** [comment]
Да, так и задуманно. Редактировать можно только контакты созданные через справочник. Импортированные нужно редактировать в Active Directory, после чего повторно запустить синхронизацию в справочнике.
Скрыть отключенные в AD контакты можно так: /pb.php?action=hide_disabled
Скрывать удаленные не предусматривал, никогда не удаляли аккаунты уволенных сотрудников, всегда обходились отключением учетки. Подумаю над этим. Возможно добавлю.
