### ISSUE TITLE
Connecting to computer , не открывает окно для подключения

### ISSUE THREAD

**Issue by serdgserdg** [pfzim/ldap-phonebook#60]
подскажите как пользоваться функцией 
https://github.com/pfzim/ldap-phonebook/blob/master/examples/msraurl.cmd

При нажатии кнопки Connecting to computer "Workstation***" из меню ничего не происходит.
C:\Windows\System32\msra.exe /offerra %param1:~8%
окно открывается без проблем

**Comment by pfzim** [comment]
Чтобы открывалась ссылка, нужно зарегистрировать URL Protocol в реестре. Пример в файле msraurl.reg.
Тогда ваш браузер сможет открывать ссылки типа `msraurl:COMPUTER_NAME`.
Имя компьютера будет передаваться в файл msraurl.cmd в качестве параметра. Таким образом вы сможете вызывать нужные вам команды.
В примере вызывается Удалённый помощник Windows (msra.exe).

**Comment by serdgserdg** [comment]
Спасибо, все получилось!
Добавил msraurl.reg  в реестр и скопировал в папку  windows файл msraurl.bat поправив в нем запуск нужной мне программы "C:\Program Files (x86)\SolarWinds\Dameware Mini Remote Control\DWRCC.exe" -c: -h: -x -a:1 -m:%param1:~8%
Очень удобно для работы
