### ISSUE TITLE
Не импортирует из XML, предварительно выгруженный телефонной книгой.

### ISSUE THREAD

**Issue by mihailkozh** [pfzim/ldap-phonebook#61]
Добрый день.
Сделал экспорт контактов в xml (Инструменты-экспорт; Просто через "Экспорт").
А вот обратно не импортирует из этого же файла. Пишет 0 успешно, ошибок 140 (общее количество контактов).
В какую сторону копать?

**Comment by mihailkozh** [comment]
Все делалось на одной версии.
[Tue Apr 11 11:26:55.831785 2023] [:error] [pid 3538] [client :52546] PHP Warning:  simplexml_load_file():      ^ in /var/www/html/pb.php on line 636, referer: http://vzdr-s-pb01.ozm.loc/pb.php?action=services

**Comment by pfzim** [comment]
Содержимое файла проверяли?
Можете файл приложить?

**Comment by mihailkozh** [comment]
я сделал файл из одной записи.
такая же ошибка, только на один контакт.
<phonebook>
<contact>
		<name> АЗОТ Начальник БВР</name>
		<phone1>3297</phone1>
		<phone2></phone2>
		<phone3></phone3>
		<mail></mail>
		<organisation>АЗОТ Майнинг</organisation>
		<departament></departament>
		<section></section>
		<position>Начальник БВР</position>
	</contact>
</phonebook>

**Comment by pfzim** [comment]
Этот формат предназначен для использования во внешнем оффлайн приложении и не предназначен для последующего импорта. Используйте "Экспорт XML".
Либо руками скорректируйте файл, измените имена ключей в выгруженном файле под формат, как при "Экспорт XML", и попробуйте импортировать.

**Comment by mihailkozh** [comment]
Такой формат должен быть?
<contact>
		<id>167</id>
		<samname></samname>
		<fname>АЗОТ Начальник БВР</fname>
		<lname></lname>
		<dep></dep>
		<org>АЗОТ Майнинг</org>
		<pos>Начальник БВР</pos>
		<pint>3297</pint>
		<pcity></pcity>
		<pcell></pcell>
		<mail></mail>
		<bday>0000-00-00</bday>
		<photo>0</photo>
		<type>0</type>
		<map>0</map>
		<x>0</x>
		<y>0</y>
		<visible>1</visible>
	</contact>

**Comment by pfzim** [comment]
Да

**Comment by mihailkozh** [comment]
Спасибо.
Я правильно понял, что в принципе при смене домена, откуда беруться данные пользователей - у меня нет другого выхода, кроме как экспортировать базу, оставить в ней только локальные контакты. Очистить базу, загрузить локальные контакты, настроить синхронизацию  с новым доменом AD?

**Comment by pfzim** [comment]
Я ошибся. Названия полей у вас почему-то из старой версии. В последней версии выглядит так:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<phonebook>
	<contact>
		<id>1</id>
		<adid></adid>
		<samaccountname></samaccountname>
		<first_name></first_name>
		<last_name></last_name>
		<middle_name></middle_name>
		<department></department>
		<organization></organization>
		<position></position>
		<phone_internal></phone_internal>
		<phone_external></phone_external>
		<phone_mobile></phone_mobile>
		<mail></mail>
		<birthday></birthday>
		<reserved1></reserved1>
		<reserved2></reserved2>
		<reserved3></reserved3>
		<reserved4></reserved4>
		<reserved5></reserved5>
		<flags>1</flags>
		<type>0</type>
		<map>0</map>
		<x>0</x>
		<y>0</y>
	</contact>
</phonebook>
```

При загрузке данных из AD сопоставление пользователей производится по атрибуту objectguid (в таблице БД соответствует колонки adid). Не понятно как они у вас сопоставятся, наверняка objectguid будут другие.
Я не совсем понимаю вашей задачи.
Если доменные контакты не важны, то думаю достаточно поменять настройки и провести синхронизацию.
Старые контакты удалятся, новые подгрузятся.

**Comment by mihailkozh** [comment]
У меня не самая последняя версия
У нас идет смена домена AD. Мне необходимо сохранить локальные контакты (добавленные вручную). Контакты из новой AD подтянутся автоматом.

**Comment by mihailkozh** [comment]
> Если доменные контакты не важны, то думаю достаточно поменять настройки и провести синхронизацию.
> Старые контакты удалятся, новые подгрузятся.
Старые не удаляются

**Comment by pfzim** [comment]
Что-то я уже стал позабывать логику работы справочника. Давно не пользуюсь им.
А если выполнить `contacts_hide_disabled` (или возможно в старой версии  `hide_disabled`), чтобы скрыть отключенные контакты?

**Comment by mihailkozh** [comment]
Отключенные контакты он скрывает, худо-бедно.
Дело в том что Справочник был моим коллегой натравлен на всю старую AD. А в новой AD  я натравил его только на определенную OU.
И у мен сейчас в базе и контакты со старого домена, и с нового (не все, почему-то) и локальные.
Хотелось бы без контактов из старого домена.

**Comment by pfzim** [comment]
А обновиться до последней версии не хотите?
Насколько старая версия у вас установлена?

**Comment by mihailkozh** [comment]
Версия 2020 года.
Обновиться с наскока не получилось. Может в пятницу\субботу займусь.

**Comment by pfzim** [comment]
У вас правильное поведение для вашей версии. Удаление учётных записей не было предусмотрено, т.к. у нас пользователи не удаляются, а блокируются при увольнении. Удаление появилось в более поздних версиях.
В вашем случае либо обновление, либо SQL запросом вычищать доменных пользователей напрямую из БД.

**Comment by mihailkozh** [comment]
Меня интересует следующий вопрос - если в пределах одной версии он не может импортрировать контакты, то сработает ли импорт на более свежей версии? К тому же структура поменялась.
Меня бы устроило очистка текущей базы, и импорт локальных контактов + синхронизация из AD, но не получается  импортировать.

**Comment by pfzim** [comment]
Между версиями менял названия полей, поэтому не загрузится. Но не вижу ничего сложного произвести их замену в текстовом редакторе.

**Comment by pfzim** [comment]
Получилось обновить? Закрываю проблему?

**Comment by mihailkozh** [comment]
Не получилось. Закрывайте.
