### ISSUE TITLE
Не синхронизируется LDAP

### ISSUE THREAD

**Issue by funtikos** [pfzim/ldap-phonebook#65]
Первичная настройка прошла успешно, но при синхронизации пишет
Exception: File: C:\xampp\htdocs\routes\contacts_sync.php[49]: ldap_parse_result return error code: , message: , ldap_error: Success Trace: #0 C:\xampp\htdocs\modules\Router.php(103): contacts_sync(Object(Core), Array, Array)
#1 C:\xampp\htdocs\pb.php(320): Router->process('contacts_sync', Array)
#2 {main}

А на экране

Response: <br />
<b>Warning</b>: ldap_search() expects at most 8 parameters, 9 given in <b>C:\xampp\htdocs\routes\contacts_sync.php</b> on line <b>34</b><br />
<br />
<b>Notice</b>: Undefined variable: controls in <b>C:\xampp\htdocs\routes\contacts_sync.php</b> on line <b>47</b><br />
<br />
<b>Warning</b>: ldap_parse_result() expects at most 6 parameters, 7 given in <b>C:\xampp\htdocs\routes\contacts_sync.php</b> on line <b>47</b><br />
{"code": 1, "message": "Exception: File: C:\\xampp\\htdocs\\routes\\contacts_sync.php[49]: ldap_parse_result return error code: , message: , ldap_error: Success Trace: #0 C:\\xampp\\htdocs\\modules\\Router.php(103): contacts_sync(Object(Core), Array, Array)\n#1 C:\\xampp\\htdocs\\pb.php(320): Router->process('contacts_sync', Array)\n#2 {main}"}

В чем может быть проблема? Несколько версий ставил, все одна ошибка

**Comment by pfzim** [comment]
Подозреваю, что у вас версия PHP старее чем 7.3.0.
Начиная с неё в указанные функции был добавлен дополнительный параметр: Support for controls added.
Обновите PHP.
