### ISSUE TITLE
Закрыт доступ к секции 0 для пользователя!

### ISSUE THREAD

**Issue by artemanisimov83** [pfzim/ldap-phonebook#66]
Закрыт доступ к секции 0 для пользователя!
Нужна помощь

**Comment by pfzim** [comment]
Это означает, что пользователь не является администратором и не может вносить правки в справочник и управлять правами доступа.

**Comment by artemanisimov83** [comment]
Какой пользователь при установке является администратором и может управлять справочником? Спасибо

**Comment by pfzim** [comment]
Тот, которого вы указали на этапе установки справочника в разделе "Local admin account".
