### ISSUE TITLE
Закрыт доступ к секции 0 для пользователя

### ISSUE THREAD

**Issue by r00ck4** [pfzim/ldap-phonebook#67]
Здравствуйте, настроил все, не могу запустить синхронизацию контактов из AD, ошибка Закрыт доступ к секции 0 для пользователя. Подскажите где настроить доступ к секции.

**Comment by r00ck4** [comment]
Разобрался самостоятельно.

**Comment by vovka142** [comment]
По

> Разобрался самостоятельно.

Подскажи как)
