### ISSUE TITLE
Изменение иконки размещения

### ISSUE THREAD

**Issue by r00ck4** [pfzim/ldap-phonebook#68]
Может знает кто, как заставить выводить не иконку на карту, а сразу фио (с тем же интерактивом соответственно)? И как запретить перетаскивание под юзером? Не хочу чтобы вообще двигались сотрудники, только под админом.

**Comment by pfzim** [comment]
Вам нужно внести соответствующие изменения вот в эту строку:
https://github.com/pfzim/ldap-phonebook/blob/07ebd8facda154ae571201465c16b488f4a96489/templates/tpl.map.php#L10

**Comment by pfzim** [comment]
В проекте такого не предусмотрено. Меняйте &lt;img /&gt; на свой &lt;div&gt;с нужным вам текстом&lt;/div&gt;. Как-то так.
