### ISSUE TITLE
AJAX Error code 500

### ISSUE THREAD

**Issue by thdonatello** [pfzim/ldap-phonebook#7]
Здравствуйте!
Заметил, что элемент номера телефона является активным, но при нажатии выходит ошибка AJAX Error code 500. Механизм колбека? Если да, то как заставить работать? Имею в сети asterisk.

**Comment by pfzim** [comment]
На Хабре просили реализовать запрос к СКУД для отображения в офисе сотрудник или нет. Я ей повесил на нажатие по номеру. Функцию обращения к БД СКУД нужно дописать под свою систему в файле inc.acs.php. А вообще на это место можно любой функционал повесить.
