### ISSUE TITLE
Добавление столбца

### ISSUE THREAD

**Issue by ZenAku** [pfzim/ldap-phonebook#70]
Добрый день.
Как добавить новую колонку, к примеру, город? В теории я понимаю какой атрибут надо забрать с лдапа (в случае города это 'l'), могу поменять вывод его значения в любом из столбцов, т.е. мобильный номер на город, а вот как добавлять новые не понимаю в каких шаблонах вносить изменения.

**Comment by pfzim** [comment]
Для такого случая в БД предусмотрены 5 неиспользуемых столбцов reserved1-5.
Заполняйте их нужными вам значениями во время синхронизации вот здесь:
https://github.com/pfzim/ldap-phonebook/blob/07ebd8facda154ae571201465c16b488f4a96489/routes/contacts_sync.php#L97-L101

И добавьте их в таблицу в файле `template/tpl.mail.php`

**Comment by ZenAku** [comment]
Спасибо, помогло. А в каком файле находится перевод названий столбцов?

**Comment by ZenAku** [comment]
Спасибо, помогло.
