### ISSUE TITLE
Ошибка синхронизации

### ISSUE THREAD

**Issue by inemo1987** [pfzim/ldap-phonebook#76]
Всем добрый день!
Проверял настройки crontab для автоматического обновления и после этого не выдает список на главной. Вкладка "Показать все" - показывает.
При запуске php -f /var/www/pb/pb.php -- --user username --password password --path contacts_sync выдает:

PHP Deprecated:  setcookie(): Passing null to parameter #2 ($value) of type string is deprecated in /var/www/pb/modules/UserAuth.php on line 286
PHP Deprecated:  setcookie(): Passing null to parameter #2 ($value) of type string is deprecated in /var/www/pb/modules/UserAuth.php on line 287
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/pb/inc.utils.php on line 774
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/pb/inc.utils.php on line 774
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/pb/inc.utils.php on line 774
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/pb/inc.utils.php on line 774

как победить?

**Comment by inemo1987** [comment]
Решил пересозданием БД.
Однако, так и не нашел решение:
В меню "Показать все" отображает всех пользователей, но если во вкладке "Главная" пропадает пользователь или несколько, как их вернуть в "главную" скриптом - не понятно.

**Comment by pfzim** [comment]
Подозреваю, что не может подключить к AD и загрузить данные о пользователях, поэтому скрывает всё, что было загружено ранее, как уже не существующие контакты.
Ошибки, которые видите при запуске скрипта, из-за различия версий PHP. Справочник написан на PHP7, у вас видимо версия новее. По идеи эти предупреждения не должны влиять на его работу.
А через веб интерфейс синхронизация проходит успешно?

**Comment by inemo1987** [comment]
Да, используется 8.2.
Через веб не пробовал, так как изначально хочется максимально автоматизировать.
Если вдруг повторится - попробую версию dev. 
Спасибо за ответ!
