### ISSUE TITLE
Сброс пароля для admin

### ISSUE THREAD

**Issue by vovka142** [pfzim/ldap-phonebook#77]
Здравствуйте. Имеется такая возможность?)

**Comment by vovka142** [comment]
Разобрался)
Кому актуально, пишу как.

переименовал **inc.config.php**
запустил **install.php**
прописал пути к БД, проверил связь
и внизу прописал пароль админу, нажал "**Create admin account**"
вернул изменённое имя **inc.config.php**
и готово)

**Comment by pfzim** [comment]
Под формой ввода логина и пароля есть ссылка для восстановления пароля. Она не сработала?
