### ISSUE TITLE
Удаление старых контактов

### ISSUE THREAD

**Issue by thdonatello** [pfzim/ldap-phonebook#9]
Скажите, синхронизация с AD проходит только в сторону добавления контактов? Например при увольнении сотрудника мы отключаем уч. запись и перемещаем ее в отдельный OU за пределами компании. После синхронизации контакт остается в списке, хотя его даже нет в OU, на который нацелена книга.
Если так, то как проще всего очистить мусорные контакты? Очистить всю БД (контакты используем только из AD) и синхронизировать?
Спасибо.

**Comment by pfzim** [comment]
Если учетные записи не удалялись из AD, тогда отключенные в AD записи можно скрыть из справочника так: `http://localhost/pb/pb.php?action=hide_disabled`

**Comment by thdonatello** [comment]
"Added 0 contacts, updated 0 contacts". Наверное по причине переноса отключенных учеток в другой OU:
define("LDAP_BASE_DN", "OU=City,DC=com,DC=company,DC=org") - для активных сотрудников, отсюда и создается книга; "OU=Disabled,DC=com,DC=company,DC=org" - для уволенных.

**Comment by pfzim** [comment]
В таком случае может в файле pb.php в строке 505 заменить `LDAP_BASE_DN` на DN нужной OU или указать на корень AD

**Comment by thdonatello** [comment]
Не указывал корень, т.к. в некоторых OU лежат контакты, которые не хотелось бы публиковать. А так да, pb.php?action=hide_disabled успешно отрабатывает на полном дереве. На будущее все же, можно ли и как лучше очищать все дерево и очищать список от удаленных?
Спасибо большое.

**Comment by pfzim** [comment]
Изменение в 505 строке повлияет только на скрытие отключенных контактов. На импорт это изменение не повлияет, поэтому можно указать на корень AD.
Других вариантов очистки справочника на данный момент не предусмотрено.

**Comment by thdonatello** [comment]
Прошу прощения, неправильно прочел Ваше сообщение, потому изменил строку в inc.config.php, она же как аргумент в pb.php. Сейчас "внаглую" в pb.php прописал, отработало как нужно. Ну, пусть так, пока устроит, лишь бы не забыть эти правки спустя время. Спасибо большое еще раз.

**Comment by pfzim** [comment]
![screenshot_28](https://user-images.githubusercontent.com/6803907/45083969-c140c380-b105-11e8-8f8b-95a9f7bf5ff2.png)

**Comment by thdonatello** [comment]
:) Прошу прощения, не уточнил. Не ручками, а скриптом. На подобии http://localhost/pb/pb.php?action=hide_disabled

**Comment by pfzim** [comment]
Так сделать не получится. Это равносильно показать все контакты.

**Comment by pfzim** [comment]
В новой версии переделал синхронизацию. Теперь удалённые контакты тоже будут скрываться.
